Add a migration to rename scopes for api_entreprise
betagouv/datapass pull request #1092
Opened 2023-06-08 08:38 UTC by Isalafont

This PR is linked to [[API Entreprise] évolution de la gestion des droits #1044](https://github.com/betagouv/datapass/pull/1044). 

See this comment with the api entreprise modifications in order to help to write the migration : 
https://github.com/betagouv/datapass/pull/1044#issuecomment-1578151472

---

_Before Migration :_ 
<img width="915" alt="Capture d’écran 2023-06-08 à 10 34 10" src="https://github.com/betagouv/datapass/assets/43042737/dc7fb4d0-5d19-4d06-8b3b-427f19a8d835">

---

_After Migration_
<img width="915" alt="Capture d’écran 2023-06-08 à 10 33 24" src="https://github.com/betagouv/datapass/assets/43042737/86689cb0-e870-4a29-9a03-4f9de1ef325e">
<img width="915" alt="Capture d’écran 2023-06-08 à 10 32 59" src="https://github.com/betagouv/datapass/assets/43042737/744d9676-8cf8-42b3-aa56-0e5be0bebc24">

2023-06-08 08:54 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [Api-Entreprise : Migration des anciens nom de scopes vers nouvelles appelations.](https://trello.com/c/WoG08As9/1895-api-entreprise-migration-des-anciens-nom-de-scopes-vers-nouvelles-appelations)

2023-06-08 16:17 UTC, skelz0r requested changes
Vu la criticité de la migration faut dump la db de prod et tester en local voir si c'est cohérent.

2023-06-08 16:17 UTC, skelz0r commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +      Enrollment.where(target_api: "api_entreprise").update_all(scopes: scopes)
```suggestion
      enrollement.update(scopes: scopes)
```

Autrement tu mets à jour TOUTE la db à chaque fois avec les scopes d'une demande. In fine on va se retrouver donc avec toutes les demandes DataPass d'API Entreprise avec les scopes de la dernière demande DataPass.

2023-06-08 16:17 UTC, skelz0r commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +    Enrollment.find_each do |enrollment|
On ne veut migrer que les demandes DataPass d'API Entreprise

```suggestion
    Enrollment.where(target_api: 'api_entreprise').find_each do |enrollment|
```

2023-06-08 16:17 UTC, skelz0r commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +  def down
cf remarques sur le `up`

2023-06-08 16:17 UTC, skelz0r commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +          scope
Je léverai une exception ici pour être sûr de bien tout migrer.

2023-06-08 16:17 UTC, skelz0r commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +          "open_data"
Tous les opens data tu peux faire un truc du genre:

```ruby
when "certificat_rge_ademe", "extrait_court_inpi"
  "open_data"
```

2023-06-08 16:17 UTC, skelz0r commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +          "associations" && "fntp_carte_pro" && "qualibat" && "certificat_rge_ademe" && "extrait_court_inpi" && "extraits_rcs" && "actes_inpi" && "conventions_collectives" && "entreprises_artisanales
cf com plus haut

2023-06-14 08:11 UTC, Isalafont commented
Hello @skelz0r, 
Je veux bien oui si cela ne te dérange pas, tu as une bien meilleure connaissance et vision de la partie api entreprise concernant l'évolution des scopes :)

2023-06-14 08:48 UTC, skelz0r commented
Très bien je reprend :)

2023-06-14 13:05 UTC, skelz0r commented
A priori on est bon, @DorineLam j'ai juste un point que je t'ai remonté sur basecamp vis à vis de `certification_opqibi` qui a complétement disparu des scopes, est-ce normal ? On a pourtant fait une migration de scope chez nous.

Faudrait aussi relire le mapping pour être sûr, j'ai relu 3 fois pour info.

2023-06-14 13:08 UTC, skelz0r commented
D'ailleurs on le voit sur le dernier screen d'isabelle qu'il manque la certification_opqibi (et l'urssaf mais j'ai corrigé ici)

2023-06-15 14:40 UTC, Isalafont commented
@skelz0r Tu me donneras ton go quand ce sera bon de ton côté (par rapport au scope `certification_opqibi` ?

2023-06-15 14:41 UTC, skelz0r commented
@Isalafont oui tkt

2023-06-15 15:00 UTC, skelz0r commented
J'ai rajouté le scope manquant, mais avant de faire un merge j'aimerai bien un double check de quelqu'un.

2023-06-16 08:52 UTC, DorineLam requested changes
@skelz0r deux petits éléments + le fait que le certif opqibi est une donnée open data, donc n'a pas besoin de scope dédié car rejoint le droit "open_data"

2023-06-16 08:52 UTC, DorineLam commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +          ["mandataires_sociaux_infogreffe", "unites_legales_etablissements_insee"]
@skelz0r je me demande s'il ne manque pas open_data ici ?

```suggestion
          ["open_data", "mandataires_sociaux_infogreffe", "unites_legales_etablissements_insee"]
```

2023-06-16 08:52 UTC, DorineLam commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +        when "effectifs_acoss"
Ici j'ai un doute sur la correspondance .... Vu que "effectifs_acoss" n'existait pas ? Mais tu as certainement fait exprès ?

2023-06-16 08:52 UTC, DorineLam commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +          "certification_opqibi"
La certification OPQIBI étant en open data, on la met dans le pack de droits open data

```suggestion
          "open_data"
```

2023-06-16 08:52 UTC, DorineLam commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +            "certificat_agence_bio"
Certification OPQIBI est open data, ajouter dans la liste

```suggestion
            "certificat_agence_bio",
            "certificat_opqibi"
```

2023-06-16 08:52 UTC, DorineLam commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +        when "certification_opqibi"
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +          "certificat_opqibi"
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": false,
Certification OPQIBI est open data, supprimer cette ligne 
```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": false,
Certification OPQIBI est open data, supprimer cette ligne 
```suggestion
        "certification_opqibi": false,
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": false,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": false,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": false,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": false,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": false,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": false,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": true,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": true,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": true,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": true,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": false,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certification_opqibi": true,
Certification OPQIBI est open data, supprimer cette ligne 

```suggestion
```

2023-06-16 08:52 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/index.js
> +  {
Supprimer ce bloc

2023-06-16 08:59 UTC, skelz0r commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +        when "effectifs_acoss"
> Vu que "effectifs_acoss" n'existait pas ? 

Si ça existait sur ce commit 86c4f1fa454aa289001d784abeaa03890d45458d

2023-06-16 09:03 UTC, DorineLam commented on backend/db/migrate/20230608080932_rename_api_entreprise_scopes_in_enrollments.rb
> +        when "effectifs_acoss"
Ok !

2023-06-16 09:15 UTC, skelz0r commented
@Isalafont vous avez un process pour importer de la données en local facilement pour tester des migrations ? Ou alors des seeds ?

2023-06-16 09:34 UTC, Isalafont commented
@skelz0r Des fixtures ont été créé, mais aucune pour `api_entreprise` surtout que la il faut créer des habilitations avec des anciens formulaires... 
Sinon il faudrait récupérer un Dump directement de l'environnement de prod ou de staging ?

2023-06-16 09:55 UTC, skelz0r commented
J'en déduis avec ta réponse que vous n'avez pas de process 😅

Je vais voir cd que je peux faire.

2023-06-16 12:39 UTC, skelz0r commented
@Isalafont on est bon j'ai testé la migration avec la db de prod c'est OK (j'ai quand même catch les erreurs au cas où mais je pense que ça sera OK).

Je veux bien que tu me ping dès que c'est en prod pour que j'inspecte les logs de la migration.

2023-06-16 13:06 UTC, Isalafont commented
@skelz0r Dès que Nico fait la MEP, on vous préviendra 👍🏻

2023-06-16 13:11 UTC, merged