`requested_changes_have_been_done` Badge ✅
betagouv/datapass pull request #1102
Opened 2023-06-15 15:00 UTC by pierreericgarcia

2023-06-15 15:00 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ I, je vois un badge état "Modifications effectuées" quand une habilitation est repassée de "A modifier" à "En cours"](https://trello.com/c/1Dd8iFf7/1806-etq-i-je-vois-un-badge-%C3%A9tat-retour-de-modifications-quand-une-habilitation-est-repass%C3%A9e-de-a-modifier-%C3%A0-en-cours)

2023-06-20 08:32 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ I, si je clique sur une habilitation, le badge "Nouveau" disparaît sur la page Accueil](https://trello.com/c/JDGBtdZZ/1907-etq-i-si-je-clique-sur-une-habilitation-le-badge-nouveau-dispara%C3%AEt-sur-la-page-accueil)

2023-06-20 09:50 UTC, Isalafont requested changes

2023-06-20 09:50 UTC, Isalafont commented on backend/app/models/enrollment.rb
> +    penultimate_event = events.order(:created_at).second_to_last
pénultième évènement ? Ce n'est pas un mot courant, pourquoi ne pas appeler la variable `second_to_last` comme la méthode ruby déjà existante ? 
Je pense que cela serait plus facile à lire.

2023-06-20 14:11 UTC, merged