Add levenshtein on global_search in FilterService
betagouv/datapass pull request #1122
Opened 2023-07-11 13:20 UTC by pierreericgarcia

2023-07-11 13:24 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U, si je tape "Commune Clamart", je tombe sur les habilitations de la Commune de Clamart (optimisation de la recherche)](https://trello.com/c/dm5hlc0X/1878-etq-u-si-je-tape-commune-clamart-je-tombe-sur-les-habilitations-de-la-commune-de-clamart-optimisation-de-la-recherche)

2023-07-12 07:28 UTC, skelz0r requested changes
Il faudrait un test pour vérifier que cela fonctionne.

2023-07-25 15:27 UTC, skelz0r requested changes
Principalement du refacto sur le test pour rendre ça plus robuste: je pense qu'il faut à minima crée un enrollment qui ne match pas pour vérifier qu'il ne remonte pas.

2023-07-25 15:27 UTC, skelz0r commented on backend/spec/services/filter_service_spec.rb
> +        params = {filter: filters}
remonte ça dans un `let` c'est plus propre

2023-07-25 15:27 UTC, skelz0r commented on backend/spec/services/filter_service_spec.rb
> +        filters = [
remonte ça dans un `let` c'est plus propre

2023-07-25 15:27 UTC, skelz0r commented on backend/spec/services/filter_service_spec.rb
> +      end
Si tu appliques les mêmes recos que plus haut, tu peux simplifier de cette manière:

```suggestion
      context "when the search term is too far from values in database" do
        let(:filters) { [ {"key" => "global_search", "value" => "commune d calmart"}.to_json ] }
        
        it { is_expected.to be_empty }
      end
```

clairement plus propre ;)

2023-07-27 07:51 UTC, skelz0r reviewed
Je trouve que le test n'est toujours pas assez explicite, et qu'en réalité il faudrait un peu refactor tout ça pour que ça soit plus clean.

Des remarques en vrac sur comment bien faire le test:

* Ne plus passer un `Enrollment.all` dans le filtre et maîtriser exactement ce qu'on y met
* Créer des enrollments qui ne match pas les critères de filtre pour être sûr que ça ne ressort pas
* Setup exactement la valeur `value` dans la création des modèles pour que ça soit indépendant de la factory
* Modifier la factory pour override ces valeurs là (via des transient)

Je request ni approve la PR, je te laisse le choix: soit tu décides de repasser sur le test et rendre ça plus robuste, soit tu ouvres un ticket avec mes recos pour refacto ça plus tard (l'un ou l'autre me convient)

2023-08-10 08:58 UTC, pierreericgarcia commented
J'ai mergé comme ça et j'ai ouvert un ticket sur le trello :)

https://trello.com/c/qsLVkfal/1954-etq-dev-je-rends-plus-robuste-le-service-de-filtre

2023-08-10 08:58 UTC, merged