Add new scopes pole_emploi_paiements
betagouv/datapass pull request #1133
Opened 2023-07-28 07:32 UTC by skelz0r

2023-07-28 07:33 UTC, skelz0r commented
@SchweisguthN @pierreericgarcia aucune idée de si je dois modifier d'autres choses, j'ai cherché dans le code je n'ai rien trouvé et c'est différent de API Entreprise 🤷

2023-07-28 08:16 UTC, Haelle approved these changes

2023-07-28 08:20 UTC, DorineLam approved these changes
Super merci

2023-07-28 08:22 UTC, DorineLam requested changes
En fait, je viens de m'apercevoir d'un problème. Peux-tu mettre le scope des paiements après pole_emploi_inscription ?

2023-07-28 08:22 UTC, skelz0r commented
Déso je vous re-request @DorineLam @Haelle car il manquait un bout

2023-07-28 08:23 UTC, skelz0r commented
> Peux-tu mettre le scope des paiements après pole_emploi_inscription ?

La liste est non-ordonnée ici, j'ai changé le bloc `groups` qui imo lui est ordonné.

2023-07-28 08:25 UTC, DorineLam commented on backend/config/data_providers.yml
> +      label: API Indemnités Pôle emploi
J'aurai gardé le nom "paiements" :

```suggestion
      label: API Paiements Pôle emploi
```

2023-07-28 08:26 UTC, DorineLam commented
> > Peux-tu mettre le scope des paiements après pole_emploi_inscription ?
> 
> La liste est non-ordonnée ici, j'ai changé le bloc `groups` qui imo lui est ordonné.

Oui ok, je trouvais ça étonnant en effet ^^ J'ai un doute sur le nom de l'API, je te l'ai mis en commentaire.
Pour le scope identité, je suis étonnée, on a ces informations ?

2023-07-28 08:27 UTC, skelz0r commented
> Pour le scope identité, je suis étonnée, on a ces informations ?

Je renvoi l'identifiant d'appel (c'est la même logique que l'autre API)

2023-07-28 08:28 UTC, skelz0r commented
> > Pour le scope identité, je suis étonnée, on a ces informations ?
> 
> Je renvoi l'identifiant d'appel (c'est la même logique que l'autre API)

Je l'ai retiré

2023-08-17 16:08 UTC, Haelle commented
@SchweisguthN @pierreericgarcia UP ?

2023-08-17 16:12 UTC, merged