Add Qualiopi France Compétences scope for API Entreprise
betagouv/datapass pull request #1161
Opened 2023-08-29 08:51 UTC by Samuelfaure

Première fois que je fais ça, j'espère ne rien avoir oublié

@DorineLam Vu que tu connais bien les cas d'usage peux-tu check mes ajouts dans le fichier `frontend/src/pages/ApiEntreprise/demarches.json` (formulaires pré-remplis) , j'ai mis par défaut `false` partout mais peut-être qu'un formulaire pré-remplis veut ce scope.

2023-08-29 09:02 UTC, skelz0r requested changes
Je pense qu'il faut aussi l'ajouter dans l'un des groupes du fichier `frontend/src/pages/ApiEntreprise/index.js` (`const groups`)

2023-08-29 09:06 UTC, skelz0r approved these changes
Techniquement c'est OK pour moi. Par contre je suis étonné que qualiopi soit dans le groupe des régularités (mais je n'ai pas la connaissance métier donc bon 🤷)

2023-08-29 09:16 UTC, Samuelfaure commented
A priori ça fait sens, me semble bien qu'on veut vérifier que l'entreprise possède les certifications pour former notamment pour avoir accès au CPF

Au cas où, poke @dorine => tu me confirmerais que Qualiopi-FC ça serait "Informations protégées de régularité sociale et fiscale" (regularités)? L'alternative étant "Informations générales"

2023-08-29 09:19 UTC, skelz0r commented
D'ailleurs je pensais que c'était de l'open data, ce n'est pas le cas ?

2023-09-04 10:18 UTC, Un3x reviewed
Good to me.

2023-09-08 11:30 UTC, DorineLam reviewed
Modulo mes quelques retours, ça m'a l'air bon :) 

Une question restera en suspens : pour quel formulaires pré-remplis d'éditeur, on coche la case "Certifications Qualiopi et France Compétences" ? @Charlottecho

2023-09-08 11:30 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certifications_qualiopi_france_competences": false,
```suggestion
        "certifications_qualiopi_france_competences": true,
```

2023-09-08 11:30 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certifications_qualiopi_france_competences": false,
```suggestion
        "certifications_qualiopi_france_competences": true,
```

2023-09-08 11:30 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certifications_qualiopi_france_competences": false,
@Samuelfaure il faut également ajouter cette ligne dans le formulaire pré-rempli `"aides_publiques"` situé juste au dessus dans le code, avec le booléen à `true`

2023-09-08 11:30 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/index.js
> +      'certifications_qualiopi_france_competences',
@Samuelfaure, c'est effectivemen ici qu'il faut le mettre. Mais du coup peux-tu renommer  le label du groupe en `'🔐 Informations protégées de régularité :'`, sans "sociale et fiscale"

2023-09-08 11:30 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/demarches.json
> +        "certifications_qualiopi_france_competences": false,
Je n'ai pas la réponse ici, donc on va effectivement laisser ce champ à false pour tous les éditeurs en attendant. Mais à mon sens, il faut qu'on voit si les éditeurs vont demander l'accès à cette donnée, et en fonction la mettre à true pour éviter aux FS d'avoir à étendre leurs droits. 

@Charlottecho est-ce que tu sais parmi les éditeurs, lesquels vont demander accès à Qualiopi ?

2023-09-08 11:31 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/index.js
> +    label: 'Certifications Qualiopi & France Compétences',
```suggestion
    label: 'Qualiopi & habilitations France compétences - CARIF-OREF',
```

2023-09-08 11:31 UTC, DorineLam commented on frontend/src/pages/ApiEntreprise/index.js
> +    label: 'Certifications Qualiopi & France Compétences',
@Samuelfaure ici, pour les labels, simplement reprendre le nom de la fiche métier et ajouter un tiret puis le nom du FD :)

2023-09-15 09:17 UTC, Samuelfaure commented on frontend/src/pages/ApiEntreprise/index.js
> +      'certifications_qualiopi_france_competences',
Je crée une issue linear, c'est pas dans le scope de cette PR

2023-09-15 09:43 UTC, merged