Made rgpd_general_agreement_validation mandatory
betagouv/datapass pull request #1189
Opened 2023-09-20 15:22 UTC by pierreericgarcia

2023-09-20 15:26 UTC, skelz0r commented on backend/app/models/enrollment/api_cpr_pro_sandbox.rb
> +  include DgfipValidationMethods
au passage ici ce n'est pas DRY, tu peux complètement refactor

2023-09-26 14:18 UTC, skelz0r commented
@pierreericgarcia ping me ou retire/rajoute moi quand t'auras finalisé (vu que tu pousses encore du code)

2023-09-27 10:33 UTC, skelz0r commented on backend/spec/factories/enrollments.rb
> +team_member_data = proc {
Ici tu devrais faire une factory:

```ruby
Factory.define do
  factory :team_member, initialize_with: Hash do
    {
      type: "responsable_metier",
      email: "user-metier@clamart.fr",
      phone_number: "0626656565",
      job: "Directeur",
      given_name: "Jean",
      family_name: "Dupont"
    }
  end
end
```

et en dessous:

```ruby
team_members { build_list(:team_member, 1) }
```

2023-09-27 10:36 UTC, skelz0r commented on backend/spec/factories/enrollments.rb
> +    trait :api_e_contacts_sandbox do
Clairement ça se refacto:

```ruby
%i[api_cpr_pro_sandbox api_e_pro_sandbox].each do |trait_name|
  trait trait_name do
    initialize_with do
      Enrollment::Kernel.const_get(trait_name.to_s.classify)
    end

    team_members { build_list(:team_member, 1) }
  end
end
```

2023-09-27 10:38 UTC, skelz0r commented on backend/spec/factories/enrollments.rb
> +    trait :api_e_contacts_sandbox do
mais du coup tu fais N factory pour tester N fois la même chose, imo fais en qu'une et un seul test si le code est 100% iso, et ceux où ça diverge tu fais aussi le test

2023-09-27 10:38 UTC, skelz0r commented on backend/spec/factories/enrollments.rb
> +    trait :api_e_contacts_sandbox do
genre `Enrollment::ApiImpotParticulierSandbox` diverge dans l'implémentation tu peux le tester aussi

2023-09-27 15:02 UTC, skelz0r requested changes
Cf mes coms

2023-09-27 15:02 UTC, skelz0r commented on backend/spec/models/enrollment/api_e_contacts_sandbox_spec.rb
> +      end
```ruby
it { is_expected.not_to be_valid }

it 'has an error on this specific field' do
  expect(enrollment.errors[:additional_content]).to include("Vous devez attester que votre organisation déclarera à la DGFiP l'accomplissement des formalités en terme de protection des données")
end
```

(petite remarque: c'est clairement pas maintenable/propre comme approche, faudrait penser à un moment soit refactor tous ces `additional_content` en db (1 champ / clé) ou utiliser de la validation jsonb https://github.com/mirego/activerecord_json_validator )

2023-10-03 12:46 UTC, pierreericgarcia commented on backend/app/models/enrollment/sandbox_enrollment.rb
> +  include DgfipValidationMethods
1 - Oui t'as raison elles sont toutes utilisées pour des API DGFIP ! 
2 - Sandbox + Production c'est dans le cas où t'as pas d'éditeur, ça te permet de faire des tests, alors que unique c'est quand t'as un éditeur c'est un peu le flow direct to production. Les formulaires uniques ne sont accessibles que par l'URL.

2023-10-03 16:01 UTC, skelz0r commented on backend/spec/factories/enrollments.rb
> +def generate_api_traits(api_list)
Tu n'as plus besoin de générer tous les traits, il te faut juste pour les 2 que tu testes plus bas.

2023-10-03 16:03 UTC, skelz0r requested changes
Jarte le code des traits qui ne sert plus, génère juste les 2 qu'il te faut (à la main).

Sinon c'est OK pour moi.

2023-10-04 11:59 UTC, merged