Ajout Editeur Coexya - ICAR
betagouv/datapass pull request #1312
Opened 2023-11-16 00:02 UTC by Miryad3108

2023-11-16 00:03 UTC, Miryad3108 commented
Dans le formulaire il y a deux contacts techniques : c'est possible d'en avoir deux dans le DataPass ? 
@DorineLam @SchweisguthN

2023-11-16 08:14 UTC, SchweisguthN commented
> Dans le formulaire il y a deux contacts techniques : c'est possible d'en avoir deux dans le DataPass ? @DorineLam @SchweisguthN

Non, ce n'est pas possible. Il y a quelquefois des formulaires où les contacts sont en doublon, mais c'est plus un bug qu'autre chose.

2023-11-28 14:30 UTC, SchweisguthN commented
@Miryad3108 Du coup, cette PR est réellement en attente de validation ? Ta question m'a mis le doute, je sais pas si tu cherchais à avoir 2 contacts ou non

2023-12-06 22:52 UTC, Miryad3108 commented
Je voulais savoir si c'était possible d'en mettre deux mais du coup j'en ai mis une (après validation de l'éditeur.
C'est bien en attente de validation maintenant @SchweisguthN . Merci :)

2023-12-12 08:50 UTC, DorineLam requested changes

2023-12-12 08:50 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +        ICAR
Ici je recommanderais de toujours sépcigier dans le titre quel est le cas d'usage, par exemple : 

```suggestion
        Coexya, solution portail familles ICAR
```

2023-12-12 08:50 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +          given_name: eric
```suggestion
          given_name: Éric
```

2023-12-12 08:50 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +          email: Eric.ROZANSKI@coexya.eu
```suggestion
          email: eric.rozanski@coexya.eu
```

2023-12-12 08:50 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +        scopes:
Ici je ne sais pas quels sont leurs scopes, mais faut bien vérifier que tous sont présents ;) (Sur API Entreprise, on a toute la liste, et on met true/false... du coup ici je ne sais pas)

2023-12-12 19:14 UTC, SchweisguthN commented on backend/config/data_providers/api_particulier.yml
> +        scopes:
Ici c'est pas du true/false, tu ne mets que les scopes cochés en true, donc c'est bon.

2023-12-12 19:15 UTC, SchweisguthN commented on backend/config/data_providers/api_particulier.yml
> +        technical_team_value:
technical_team_type et value ne doivent pas rester vide, sinon ça veut dire que les utilisateurs ne verront pas Coexya dans la liste des éditeurs de "Qui implémente l'API"

2023-12-12 22:17 UTC, Miryad3108 commented on backend/config/data_providers/api_particulier.yml
> +        technical_team_value:
C'est modifié, merci

2023-12-15 08:06 UTC, DorineLam approved these changes

2023-12-15 09:27 UTC, merged