can create an enrollment copy if previous copy has been archived
betagouv/datapass pull request #1321
Opened 2023-11-22 10:50 UTC by Isalafont

- model : validation -> Add a scope condition in enrollment model to exclude copied enrollment with status archived
- modification for policy
- add test but will need review to optimize it

2023-11-22 10:59 UTC, pierreericgarcia approved these changes

2023-11-22 11:01 UTC, skelz0r requested changes
Cf mes coms

2023-11-22 11:01 UTC, skelz0r commented on backend/app/models/enrollment.rb
>    def already_been_copied?
Cette méthode me semble inutile: elle est utilisée uniquement dans la policy, ce qui devrait  1. être une responsabilité du modèle 2. est redondant donc avec le modèle. 

Je pense qu'il faut:

1. Nettoyer ceci dans la policy
2. Vérifier via un test qu'on a encore bien l'erreur renvoyé (si il n'est pas déjà fait).

2023-11-22 11:01 UTC, skelz0r commented on backend/app/models/enrollment.rb
> +
```suggestion
```

a la lumière de mon commentaire sur la validation.

2023-11-22 12:06 UTC, Isalafont commented on backend/app/models/enrollment.rb
>    def already_been_copied?
Effectivement on a bien un test pour voir l'erreur renvoyé concernant ce policy. 
Je regarde tout ça, merci

2023-11-27 16:29 UTC, skelz0r requested changes
quelques petits changements

2023-11-27 16:29 UTC, skelz0r commented on backend/app/controllers/enrollments_controller.rb
> +        {title: "Cette demande a déjà été copiée", message: copied_enrollment.errors.full_messages.join("\n")}
Je pense qu'on peut refactor ici et remonter dans un `render_error` défini de cette manière là:

```ruby
def render_error(title:, model:)
  render status: :unprocessable_entity, json: {
    title: title,
    message: copied_enrollment.errors.full_messages.join("\n")
  }
end
```

On pourra du coup normaliser l'ensemble des erreurs.

D'ailleurs @pierreericgarcia petite remarque: ici https://github.com/betagouv/datapass/blob/master/backend/app/controllers/opinions_controller.rb#L30 je renvoie un tableau en json avec les erreurs, ce qui n'est pas consistant avec cette gestion d'erreur (mais comme c'est +/- caché .. c'est dur de savoir si c'est la seule différence), pourquoi avoir accepté ce nouveau format d'erreurs ? 
Est-ce que tu le traites btw ?

2023-11-27 16:29 UTC, skelz0r commented on backend/app/models/enrollment.rb
> +                                                  message: "L’action que vous essayez de faire est impossible, car une copie de l’habilitation existe déjà. Pour continuer, veuillez utiliser cette cop
```suggestion
  validates :copied_from_enrollment, uniqueness: {
    scope: :copied_from_enrollment, 
    conditions: -> { where.not(status: "archived") },
    if: :copied_from_enrollment_present?,
    message: "L’action que vous essayez de faire est impossible, car une copie de l’habilitation existe déjà. Pour continuer, veuillez utiliser cette copie."
  }
```

plus lisible

2023-11-27 16:29 UTC, skelz0r commented on backend/spec/controllers/enrollments/copy_spec.rb
> +                expect(JSON.parse(copy_enrollment.body)).to eq(expected_response_hash)
```suggestion
                expect(JSON.parse(copy_enrollment.body)).to eq({
                  "title": "Cette demande a déjà été copiée",
                  "message": "L’action que vous essayez de faire est impossible, car une copie de l’habilitation existe déjà. Pour continuer, veuillez utiliser cette copie."
                })
```

2023-11-27 16:29 UTC, skelz0r commented on backend/spec/models/enrollment_spec.rb
> +  describe "validations" do
```suggestion
  describe "copy validations" do
```

2023-11-27 16:29 UTC, skelz0r commented on backend/spec/models/enrollment_spec.rb
> +      expect(new_copy).not_to be_valid
Techniquement ce n'est pas une `copy` que tu fais ici, il faudrait utiliser la méthode `copy`.

```suggestion
      create(:enrollment, :franceconnect, status: "validated", copied_from_enrollment_id: enrollment.id, organization_kind: :clamart, user: enrollment_creator)
      expect(enrollment.copy(user)).not_to be_valid
```

idem plus bas.

2023-11-28 07:42 UTC, Isalafont commented on backend/app/controllers/enrollments_controller.rb
> +        {title: "Cette demande a déjà été copiée", message: copied_enrollment.errors.full_messages.join("\n")}
Oh top, effectivement en diguant sur stackoverflow, j'ai vu passer cette méthode.

2023-11-28 07:58 UTC, Isalafont commented on backend/app/models/enrollment.rb
> +                                                  message: "L’action que vous essayez de faire est impossible, car une copie de l’habilitation existe déjà. Pour continuer, veuillez utiliser cette cop
Top merci !! Effectivement ce sera bcp plus propre!

2023-11-28 08:13 UTC, Isalafont commented on backend/spec/models/enrollment_spec.rb
> +      expect(new_copy).not_to be_valid
Rectifié 👍🏻

2023-11-28 08:20 UTC, Isalafont commented on backend/app/models/enrollment.rb
> +      end
Effectivement ce serait plus propre, ça allegerait le model ! Je serait partante pour le faire en pair pro un jour si tu as le temps ! Je n'ai encore jamais fait d'organizer  😄

2023-11-28 08:26 UTC, skelz0r commented on backend/app/models/enrollment.rb
> +      end
Tu peux déjà lire le code existant. Tu vas voir c'est loin d'être compliqué (c'est même le but: que ça soit ultra simple)

2023-11-28 08:28 UTC, Isalafont commented on backend/app/controllers/enrollments_controller.rb
> +    render status: :unprocessable_entity, json: {
Est ce qu'il ne serait pas mieux d'avoir un status `forbidden` ici plutôt qu'un `unprocessable entity` ?

2023-11-28 08:45 UTC, Isalafont commented on backend/app/controllers/enrollments_controller.rb
> +    render status: :unprocessable_entity, json: {
Parfait, je renomme la méthode alors. 👍🏻

2023-11-28 08:47 UTC, skelz0r requested changes
2 petits trucs, tu peux merger direct si ça passe les tests

2023-11-28 08:47 UTC, skelz0r commented on backend/app/controllers/enrollments_controller.rb
> +  def render_error(title:, model:)
1. Je remonterai ça dans l'application controller
2. A la lumière de nos échanges je le renommerai en `render_model_errors`

2023-11-28 08:47 UTC, skelz0r commented on backend/app/models/enrollment.rb
> +    if copied_enrollment.save
je remonterai ça juste avant le `team_members.each` au cas où

2023-11-28 09:03 UTC, skelz0r commented
je ferai un squash en 1 commit aussi

2023-11-28 09:23 UTC, Isalafont commented on backend/app/models/enrollment.rb
> +    if copied_enrollment.save
on a besoin de l'email du `demandeur` pour pouvoir save la copie et pour cela il faut d'abord copier les `team_members`...

2023-11-28 10:00 UTC, Isalafont commented
> je ferai un squash en 1 commit aussi

Alors je ne suis pas sure de moi pour le faire niveau commande git... si la PR est ok pour toi on peut le faire via github directement il me semble ?

2023-11-28 10:01 UTC, skelz0r commented
Fait un `Rebase and merge` du coup.

2023-11-28 10:31 UTC, merged