Register company/contacts to Hubspot for API Entreculier and FC
betagouv/datapass pull request #1341
Opened 2023-12-01 15:05 UTC by skelz0r

Closes https://linear.app/pole-api/issue/DAT-175/brancher-datapass-and-hubspot

2023-12-01 15:14 UTC, skelz0r commented
Y'a eu un peu de flemme sur les tests (car c'est peu critique et c'est du code qui change tout le temps). Y'a ~95% de coverage sur le code intéressant, ça prouve que les calls sur les objets non mock sont OK.

Si y'a une erreur ça passera dans Sentry.

bref, imo c'est good enough

2023-12-01 15:15 UTC, skelz0r commented
@Haelle ça peut t'intéresser aussi

2023-12-01 15:21 UTC, skelz0r commented
Autre point important: j'ai testé en cli depuis ma machine pour vérifier que l'interface de l'API de HubSpot était bien respectée.

2023-12-04 08:30 UTC, Un3x reviewed
Dans ces sujets de service + client perso j'aime bien utiliser le pattern adapter. Après c'est probablement overkill ici, mais en on peut vaguement s'inspirer en essayant de faire un minimum de modification.

Dans ce cas, je retirerais la terminologie 'Hubspot' d'un maximum de chose en dehors du client HubsportApi.

Voir le worker comme un service de registration de CRM qui utilise un client qui soit hubspot ou un autre histoire de décorrélé les deux. Si on change de CRM ou on en ajoute un 2nd, on a juste a changer la méthode crm_client, et ajouter un nouveau AnotherCrmAPI.

2023-12-04 08:30 UTC, Un3x commented on backend/app/workers/register_organization_with_contacts_on_hubspot_worker.rb
> +class RegisterOrganizationWithContactsOnHubspotWorker < ApplicationWorker
Je partirai sur un naming dans ce genre : RegisterOrganizationWithContactsOnCrmWorker

2023-12-04 08:30 UTC, Un3x commented on backend/app/workers/register_organization_with_contacts_on_hubspot_worker.rb
> +  end
```suggestion
  def crm_client
    @crm_client ||= HubspotApi.new
  end
```

2023-12-04 08:44 UTC, Isalafont approved these changes

2023-12-04 08:44 UTC, Isalafont commented on backend/app/workers/register_organization_with_contacts_on_hubspot_worker.rb
> +class RegisterOrganizationWithContactsOnHubspotWorker < ApplicationWorker
Je suis d'accord, pour le moment on utilise HubSpot mais si nous sommes amenés a intégrer un autre CRM dans l'avenir, je suis pour faire un worker plus générique.

2023-12-04 08:49 UTC, Un3x approved these changes

2023-12-04 11:59 UTC, Samuelfaure approved these changes
Je chipote 2 fois juste parce que trop d'énergie today

2023-12-04 11:59 UTC, Samuelfaure commented on backend/app/workers/register_organization_with_contacts_on_crm_worker.rb
> +  end
Si on reprend cette classe dans le rewrite Datapass on utilisera le I18n ici plutôt right?

2023-12-04 11:59 UTC, Samuelfaure commented on backend/app/services/hubspot_api.rb
> +  end
Petite incohérence de wording dans cette classe;

Ailleurs que dans cette classe tu utilises le terme 'CrmClient' pour ne pas dépendre de quel CRM on utilise j'imagine

Ici la classe est HubspotApi puique les formats sont rédigés à la façon de Hubspot

Mais du coup utiliser les termes `crm_api_client` me parait revenir à une notion d'indépendance de hubspot donc c'est pas très cohérent, je remplacerais `crm_api_client` par `hubspot_api_client`

Mais en vrai osef parce que je chipote de ouf + on va tout recoder

2023-12-06 14:18 UTC, Haelle requested changes
Il faut envoyer plus d'info à Hubspot cf mes comms

2023-12-06 14:18 UTC, Haelle commented on backend/app/workers/register_organization_with_contacts_on_crm_worker.rb
> +  end
en vrai on pourrait écraser cette info, elle provient de Datapass

2023-12-06 14:18 UTC, Haelle commented on backend/app/workers/register_organization_with_contacts_on_crm_worker.rb
> +      n_datapass: enrollment.id.to_s
Ici faut ajouter: 
- type d'entité : Fournisseur de service partout
- bouquet: API Part/Ent/FC
- solution logicielle : démarche/formulaire pré-rempli
- Intégrateur : Qui implémentera l’API ?
  - Votre équipe de développeur
  - Label de l'entreprise (on se tape sur siret)
  - Autre : peut-on faire des create_or_update dans Hubspot ? (oui) si oui/pas trop relou, ajouter sous la forme Autre: INPUT

2023-12-06 14:54 UTC, Haelle commented on backend/app/workers/register_organization_with_contacts_on_crm_worker.rb
> +      n_datapass: enrollment.id.to_s
vu IRL on peut merger en l'état on itérera pour ajouter ça ensuite

2023-12-11 13:34 UTC, merged