Propose de nouveau noms pour les scopes de l'API étudiant
betagouv/datapass pull request #1412
Opened 2024-02-16 18:36 UTC by DorineLam

2024-02-20 10:38 UTC, Un3x requested changes

2024-02-20 10:38 UTC, Un3x commented on backend/config/data_providers/api_particulier.yml
> +    - value: mesri_inscription_etudiant
Je dis peut être une bêtise mais il me semble que si tu change la value alors les utilisateurs ayant l'anciens scope n'auront plus accès à cette donnée.
Sauf migration à faire de notre côté + datapass je présume.

2024-02-20 10:48 UTC, skelz0r commented on backend/config/data_providers/api_particulier.yml
> +    - value: mesri_inscription_etudiant
Surtout que sans synchro ça va casser partout.
En lisant le ticket je ne comprends pas le problème, ni ce que ce changement résout 🤷

2024-02-21 11:09 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +    - value: mesri_inscription_etudiant
Hello, je suis désolée mais je ne comprends pas où est le problème de ma PR.
Voilà ce que j'ai cherché à faire : 

- Changer l'ordre des cases à cocher
- Changer les labels des scopes (qui sont faux)

je n'ai pas changé les values, le diff reflète mal ça car j'ai changé l'ordre

2024-02-21 11:23 UTC, skelz0r commented on backend/config/data_providers/api_particulier.yml
> +    - value: mesri_inscription_etudiant
Okkk en effet changer l'ordre et les valeurs dans le même commit n'aide pas.

Dans ce cas là je ne vois pas d'inconvénient.

2024-02-21 12:26 UTC, Un3x commented on backend/config/data_providers/api_particulier.yml
> +    - value: mesri_inscription_etudiant
Ah oui ok, en regardant le diff j'avais l'impression que tu avais changé la value et non l'ordre.
Dans ce cass pas de soucis oui :)

2024-02-23 12:55 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +    - value: mesri_inscription_etudiant
Intéressant, la prochaine fois je ferai deux commits séparés. Merci de vos retours

2024-02-23 12:55 UTC, DorineLam commented
@Un3x @skelz0r je veux bien votre validation pour pouvoir merger du coup :)

2024-02-24 14:29 UTC, skelz0r approved these changes

2024-02-29 16:27 UTC, merged