Ajout éditeur Agedi
betagouv/datapass pull request #1510
Opened 2024-06-18 14:11 UTC by Miryad3108

Ajout nouvel éditeur (pour FS pilotes FQF)

2024-06-18 14:42 UTC, Isalafont commented
Je laisse Dorine faire une passe sur la PR et lorsque tout est Ok on passera les infos du responsable technique dans les credentials afin de les "cacher".

2024-06-18 14:56 UTC, skelz0r commented
Il n'y a pas cette feature sur la v1 @Isalafont 

Si c'est OK techniquement tu peux merger/déployer je pense.

2024-06-18 16:36 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +        Proxima.ENF, Tarification services municipaux / Portail Famille, Données
@skelz0r @Isalafont c'est quoi la différence entre label et intitulé (dans state) ?

2024-06-18 16:44 UTC, skelz0r commented on backend/config/data_providers/api_particulier.yml
> +        Proxima.ENF, Tarification services municipaux / Portail Famille, Données
Il me semble que `label` est ce qui est affiché quand tu choisis le formulaire, et i`ntitulé` est l'intitulé de la demande que l'on pré-rempli

2024-06-19 14:23 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +        Proxima.ENF, Tarification services municipaux / Portail Famille, Données
@Miryad3108 preneuse d'échanger avec toi sur les titres des formulaires éditeur pour qu'on les harmonise et surtout qu'on les raccourcisse :)

2024-06-21 08:40 UTC, DorineLam reviewed
@Miryad3108 suite à notre discussion

2024-06-21 08:40 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +        Proxima.ENF, Tarification services municipaux / Portail Famille, Données
```suggestion
        Proxima.ENF | Portail Famille
```

2024-06-21 08:40 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +          Service Périscolaire, Restauration Scolaire, Extrascolaire, Accueil des
```suggestion
          Proxima.ENF | Portail Famille
```

2024-06-21 08:40 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +          Le logiciel Proxima.ENF permet la mise à jour des données familles dans le cadre d'un logiciel de gestion de l'accueil de l'enfance.
Ajouter la liste des services possibles

2024-06-27 13:54 UTC, skelz0r requested changes

2024-06-27 13:54 UTC, skelz0r commented on backend/config/data_providers/api_particulier.yml
> +        CNAF
```suggestion
        Proxima.ENF / Portail Famille,CNAF
```

Pour être consistant avec le reste

2024-06-27 13:54 UTC, skelz0r commented on backend/config/data_providers/api_particulier.yml
> +          loisirs
Cet intitulé est étrange. Comparé aux autres ça n'a rien à voir, pourquoi ne pas décrire ce que ça fait, comme par exemple "Calcul de la tarification pour la facturation des services périscolaires" (waigeo)

2024-06-28 15:04 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +          loisirs
@skelz0r on a vu avec Miryad, on souhaite changer la logique et donc plutôt introduire cette nouvelle façon de présenter le formulaire (Nom de la solution | Cas d'usage synthétique). Je vais faire un commit qui uniformise.

2024-06-28 15:16 UTC, skelz0r commented on backend/config/data_providers/api_particulier.yml
> +          loisirs
ça ne sert à rien ça va complètement changer sur la v2, qui va arriver imo semaine pro 🤷

2024-06-28 15:43 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +          loisirs
Oui mais de tout façon fallait modifier tous ces titres qui n'avaient pas de sens. Comme ça le contenu que tu prendras sera bon.

2024-06-28 16:02 UTC, skelz0r commented on backend/config/data_providers/api_particulier.yml
> +          loisirs
Si je prend le contenu comme ça ça va clairement pas aller, vu que sur la v2 la donnée est structurée 🤷
Je vais me débrouiller pour réadapter.

2024-06-28 16:12 UTC, DorineLam commented on backend/config/data_providers/api_particulier.yml
> +          loisirs
Ok en tout cas, c'est plus structuré maintenant 😅 mais probablement pas assez.

2024-07-01 04:52 UTC, Miryad3108 commented on backend/config/data_providers/api_particulier.yml
> +          loisirs
J'ai structuré comme ça dans le tableau pour la v2 @skelz0r mais tu as dû voir.
L'un d'entre vous peut faire une review de sorte à pouvoir merger la PR pour que je puisse faire compléter la demande à la commune pilote cliente de cet éditeur ? :)

2024-07-01 07:53 UTC, skelz0r commented on backend/config/data_providers/api_particulier.yml
> +          loisirs
En effet ligne 32, mais c'est le seul titre sous ce format, et ça risque d'être peu lisible sur la v2 (car il y a aura le nom de l'éditeur déjà inscrit dans la carte/le header en plus du titre).
Comme je disais, je vais me débrouiller

2024-07-01 07:53 UTC, skelz0r approved these changes

2024-07-01 09:54 UTC, merged