Feat/api particulier impot new scope infobulle
betagouv/datapass pull request #523
Opened 2022-05-13 16:42 UTC by Isalafont

Ajout des checkbox supplémentaires + infobulles  / Suppréssion de l'infobulle non nécéssaire. 

- [X] Evolution 2
- [X] Evolution 3
- [X] Evolution 4
- [X] Evolution 5
---

❓: Est ce que l'on effectue un changement de largeur des Info bulles. La largeur est de 130px actuellement. 

![Capture d’écran 2022-05-13 à 18 03 23](https://user-images.githubusercontent.com/43042737/168329164-e73d8cc4-44a3-4783-8656-e8b5c847957c.png)

2022-05-13 16:42 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U d'API Impôt Particulier, je vois les nouveaux scopes et infobulles demandés](https://trello.com/c/s2WILGqA/1422-etq-u-dapi-imp%C3%B4t-particulier-je-vois-les-nouveaux-scopes-et-infobulles-demand%C3%A9s)

2022-05-16 12:50 UTC, rdubigny requested changes

2022-05-16 12:50 UTC, rdubigny commented on frontend/src/pages/DgfipPages/api-impot-particulier-common.js
> +        dgfip_annee_n_moins_4: false,
Il faut également ajouter ces scopes dans la démarche par défaut 😁

2022-05-16 12:53 UTC, rdubigny approved these changes

2022-05-16 12:54 UTC, rdubigny commented
il y a encore 2 choses à vérifier sur cette PR : 

- [ ] le nom des scopes
- [ ] le design des longues infobulles

2022-05-30 16:06 UTC, Isalafont commented
Le design des Infobulles sera traité dans un ticket différent.

2022-06-02 13:20 UTC, rdubigny requested changes

2022-06-02 13:20 UTC, rdubigny commented on frontend/src/pages/DgfipPages/api-impot-particulier-common.js
> +      'En cochant cette case, vous optez pour récupérer les informations de l’avant-dernière année, lorsque celles de la dernière année ne sont pas disponibles.\n\nCette option n’est pas possible si
```suggestion
      'En cochant cette case, vous optez pour récupérer les informations de l’avant-dernière année, lorsque celles de la dernière année ne sont pas disponibles.\n\nCette option n’est pas possible si vous souhaitez des données fournies uniquement par la ressource facture /avis IR.\n\nPour plus de précisions, consulter la documentation présente dans la rubrique « Comment choisir les données ? »',
```

2022-06-02 13:20 UTC, rdubigny commented on frontend/src/pages/DgfipPages/api-impot-particulier-common.js
> +      'En cochant cette case, vous optez pour récupérer les données fiscales de la période après décès d’un contribuable marié ou pacsé (à défaut aucune données fiscale n’est transmise).\n\nCette opt
```suggestion
      'En cochant cette case, vous optez pour récupérer les données fiscales de la période après décès d’un contribuable marié ou pacsé (à défaut aucune donnée fiscale n’est transmise).\n\nCette option n’est pas possible si vous souhaitez des données fournies uniquement par la ressource facture /avis IR.\n\nPour plus de précisions, consulter la documentation présente dans la rubrique « Comment choisir les données ? »',
```

2022-06-02 13:20 UTC, rdubigny commented on frontend/src/pages/DgfipPages/api-impot-particulier-common.js
> +      'Cette donnée n’intègre pas la taxation des revenus au taux effectif ou au taux proportionnel. Une expression de besoin spécifique est à réaliser si, après échanges avec DGFIP, ces types de tax
```suggestion
      'Cette donnée n’intègre pas la taxation des revenus au taux effectif ou au taux proportionnel. Une expression de besoin spécifique est à réaliser si, après échanges avec DGFiP, ces types de taxation sont nécessaires.\n\nPour plus de précisions, consulter la documentation présente dans la rubrique « Comment choisir les données ? »',
```

2022-06-07 09:58 UTC, rdubigny approved these changes

2022-06-07 10:08 UTC, merged