fix scopes
betagouv/datapass pull request #541
Opened 2022-05-23 10:35 UTC by etienne0101

2022-05-23 15:48 UTC, rdubigny requested changes

2022-05-23 15:48 UTC, rdubigny commented on frontend/src/pages/AgentConnectFs.js
> +    value: 'OpenID',
@etienne0101 la bonne value ici est `openid` je pense (c'est le cas pour FranceConnect en tout cas). Il faut que cette valeur corresponde aux scopes définis dans leur doc technique pour que le mécanisme fonctionne.

2022-05-24 08:23 UTC, Isalafont approved these changes

2022-05-24 08:24 UTC, Isalafont approved these changes

2022-05-25 15:07 UTC, rdubigny approved these changes

2022-05-25 15:07 UTC, merged