Feat/email alert when unknowed editor field
betagouv/datapass pull request #543
Opened 2022-05-23 16:19 UTC by Isalafont

2022-06-02 13:10 UTC, rdubigny requested changes

2022-06-02 13:10 UTC, rdubigny commented on backend/spec/controllers/enrollments/change_state_spec.rb
> +              datapass_email = ActiveJob::Base.queue_adapter.enqueued_jobs.last
le nom de variable `datapass_email` n'est pas suffisament précis. En réalité l'objet manipulé n'est pas un email et datapass désigne l'ensemble de l'application.

2022-06-02 13:10 UTC, rdubigny commented on backend/spec/controllers/enrollments/change_state_spec.rb
> +              datapass_email = ActiveJob::Base.queue_adapter.enqueued_jobs.last
Ce test n'est pas assez robuste, si l'ordre des emails envoyés change (i.e. le mail notification_email_unknown_software n'est plus le dernier mail envoyé) le test va casser pour une mauvaise raison. Une logique plus robuste serait de chercher dans la queue le job qui nous intéresse. Par exemple avec `find` : 

```
ActiveJob::Base.queue_adapter.enqueued_jobs.find {|job| job["arguments"][1] == "notification_email_unknown_software"}
```

2022-06-03 14:43 UTC, Isalafont commented on backend/app/notifiers/concerns/email_notifier_methods.rb
> +      template: "notify_unknown_software"
J'ai retiré tous les parameters et la methode `.with()` qui oblige à les rajouter.

2022-06-07 12:27 UTC, rdubigny requested changes

2022-06-07 12:27 UTC, rdubigny commented on backend/app/mailers/enrollment_mailer.rb
> +    @enrollment = Enrollment.find(params[:enrollment_id])
`params[:enrollment_id]` and `params[:enrollment_id]` are not defined here. You should add this params when calling this fonction with `EnrollmentMailer.with(...)`

2022-06-07 16:51 UTC, rdubigny approved these changes

2022-06-07 16:51 UTC, merged