add class to helper tooltip
betagouv/datapass pull request #549
Opened 2022-05-31 16:11 UTC by Isalafont

when content text is wider than 140 characters
an helper-large class is add to adjust helper tooltip to min-width to 350px.

2022-05-31 16:17 UTC, Isalafont commented
A merger après [PR 523 - scope et infobulles](https://github.com/betagouv/datapass/pull/523)

2022-06-02 13:57 UTC, rdubigny requested changes

2022-06-02 13:57 UTC, rdubigny commented on frontend/src/components/atoms/Helper/style.css
> +.helper-large::after {
ne fonctionne pas chez moi. Je pense qu'il faut être plus précis sur le sélecteur CSS pour augmenter la priorité de la règle et évité qu'elle soit override par d'autres règles
```suggestion
.helper.helper-large::after {
```

2022-06-02 14:50 UTC, Isalafont commented
merci 🙏 j'ai effectué le changement.

2022-06-07 08:42 UTC, rdubigny commented on frontend/src/components/atoms/Helper/index.js
> +const Helper = ({ title }) => {
```suggestion
const Helper = ({ title = '' }) => {
```

2022-06-07 08:43 UTC, rdubigny approved these changes

2022-06-07 09:52 UTC, rdubigny commented on frontend/src/components/atoms/Helper/index.js
> +const Helper = ({ title }) => {
```suggestion
const Helper = ({ title = '' }) => {
```

2022-06-07 09:56 UTC, merged