Feat/display stats api
betagouv/datapass pull request #556
Opened 2022-06-07 16:01 UTC by Isalafont

Add a BlackList logic to hide `HIDDEN_DATA_PROVIDER_WITH_ENROLLMENTS_IN_PRODUCTION_ENV` in 
- frontend/src/components/templates/Stats.js

reproduce logic to 
- frontend/src/components/templates/PublicEnrollmentList.js

2022-06-27 16:40 UTC, Isalafont commented
🆘 GIT : Need to removed all the Merged commits after Rebase.

2022-06-29 12:47 UTC, rdubigny requested changes

2022-06-29 12:47 UTC, rdubigny commented on frontend/src/components/templates/Stats.js
> +          {Object.keys(DATA_PROVIDER_PARAMETERS)
can you put this in a separate variable ? it's quite a load of logic to be put within jsx

2022-06-29 12:47 UTC, rdubigny commented on frontend/src/config/data-provider-parameters.tsx
> +export const HIDDEN_DATA_PROVIDER_WITH_ENROLLMENTS_IN_PRODUCTION_ENV = [
I do not think the '_WITH_ENROLLMENTS_IN_PRODUCTION_ENV' makes much sense in this new variable name.

We should simplify to 'HIDDEN_DATA_PROVIDER_LABELS'

2022-07-05 12:33 UTC, merged