Feat/ stats-filter-api-services
betagouv/datapass pull request #563
Opened 2022-06-13 12:28 UTC by Isalafont

Filter the stats with a target_api_list params

- [ ] Add a target_api_list Array params in the Stats_controller 
- [ ] Raise an Error if the target_api key does not exist. 
- [ ] Add Test
- [ ] Filter the stats in the frontend.

2022-06-13 13:03 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U, je vois deux nouveaux boutons sur la page stats : Toutes les habilitations et Tous les services](https://trello.com/c/2ZLcsfHz/1400-etq-u-je-vois-deux-nouveaux-boutons-sur-la-page-stats-toutes-les-habilitations-et-tous-les-services)

2022-06-29 14:11 UTC, rdubigny requested changes

2022-06-29 14:11 UTC, rdubigny commented on backend/app/controllers/stats_controller.rb
> +        target_api_list = JSON.parse(params[:target_api_list])
either access target_api_list with "params.permit(:target_api_list)" or with "params[:target_api_list]" but you should be consistent with L13

2022-06-29 14:11 UTC, rdubigny commented on frontend/src/components/templates/Stats.js
> +    let result = [];
Variable initializer is redundant 
```suggestion
    let result;
```

2022-06-29 14:11 UTC, rdubigny commented on frontend/src/components/templates/Stats.js
> +      result = await getAPIStats(apiList);
plz factorize theses calls (we can do that in a PP session)

2022-06-29 14:11 UTC, rdubigny commented on frontend/src/components/templates/Stats.js
> +        console.error(
there can be other errors here, do not catch error this way (we can do that in a PP session)

2022-06-30 14:08 UTC, Isalafont commented on backend/spec/controllers/stats_controller_spec.rb
> +    before do
After some research, `:let` is lazily evaluated and will never be instantiated if you don't call it, while `:let!` is forcefully evaluated before each method call.

So calling `before do` in this case is the same than calling`let!`.

2022-07-01 07:21 UTC, Isalafont commented on backend/app/controllers/stats_controller.rb
> +        raise ActionController::BadRequest, "Invalid DataProviderConfig keys in target_api_list"
I had a method to raise an error in case of `target_api_list` variable is a string and not an Array, 
as it wasn't raise an JSON::ParsesError.

2022-07-05 13:02 UTC, merged