Chore/refacto organisation section
betagouv/datapass pull request #577
Opened 2022-06-22 14:19 UTC by Isalafont

2022-06-28 07:12 UTC, Isalafont commented
⚠️ Rebase first  #572 then merge.

2022-06-29 14:21 UTC, rdubigny requested changes

2022-06-29 14:21 UTC, rdubigny commented on frontend/src/components/organisms/form-sections/OrganisationSection/PersonalInformationCard.js
> +  // const onDisconnectionModal = () =>
remove comment

2022-06-29 14:21 UTC, rdubigny commented on frontend/src/components/organisms/form-sections/OrganisationSection/DisconnectionModalCard.js
> +  setUrlForDisconnectionPrompt,
the setUrlForDisconnectionPrompt props should not be necessary. Plz remove this and replace it with more readable props. (PP session might be usefull here)

2022-06-29 14:26 UTC, rdubigny requested changes

2022-06-29 14:26 UTC, rdubigny commented on frontend/src/components/organisms/form-sections/OrganisationSection/OrganisationCard.js
> +export const OrganisationCard = ({}) => {
remove empty object

2022-06-30 15:37 UTC, rdubigny approved these changes

2022-06-30 15:38 UTC, merged