Display message box and button
betagouv/datapass pull request #633
Opened 2022-07-19 10:31 UTC by Isalafont

add a SVG EditFillIcon file to match the Figma but not sure how to display it in the button ? 

![Capture d’écran 2022-07-19 à 12 12 46](https://user-images.githubusercontent.com/43042737/179731725-585580b0-bb5b-4e8c-a7ca-dbe3bddf4220.png)

2022-07-19 13:36 UTC, Isalafont commented
2nde Version : 

**With notification**
![Capture d’écran 2022-07-19 à 15 34 18](https://user-images.githubusercontent.com/43042737/179763432-07dcafd2-4e59-453e-9942-de672d536119.png)

**Without notification**
![Capture d’écran 2022-07-19 à 15 36 01](https://user-images.githubusercontent.com/43042737/179763716-c2536b6a-e9cb-4d1e-9a14-6971a3840a19.png)

2022-07-27 14:48 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U, lorsque je clique sur "Envoyer votre message", je vois mon message apparaître dans l'historique de la demande (Sans design)](https://trello.com/c/zvWp2k8J/1495-etq-u-lorsque-je-clique-sur-envoyer-votre-message-je-vois-mon-message-appara%C3%AEtre-dans-lhistorique-de-la-demande-sans-design)

2022-07-28 13:07 UTC, rdubigny requested changes

2022-07-28 13:07 UTC, rdubigny commented on frontend/src/components/templates/Form/FormSectionsContainer.js
> +export const FormSectionsContainer = ({ children }) => {
FormSectionsContainer n'est pas un nom de composant suffisament explicite. 

Ce composant sert à injecter le contexte qui permet d'ouvrir la boite de dialogue pour écrire un message.

Suggestion : OpenMessagePromptContextProvider

2022-07-28 13:41 UTC, SchweisguthN commented on frontend/src/components/organisms/form-sections/HeadSection/MessageFeed.js
> +      Si vous avez une question vous pouvez à présent laisser un message aux
Oui ça me semble fair. En effet, le message n'est pas adapté, mais en les prévenant ça devrait aller. Mais en effet, dans un second temps ce message devrait être conditionné au rôle de la personne qui le voit (demandeur ou instructeur).

2022-08-18 15:44 UTC, closed without merging