Allow user_is_demandeur to send message
betagouv/datapass pull request #637
Opened 2022-07-20 13:51 UTC by Isalafont

2022-07-20 13:51 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U, lorsque je clique sur le bouton "Rédiger un message", je scrolle vers le cadre de rédaction de message en bas de page](https://trello.com/c/UTML2JwM/1494-etq-u-lorsque-je-clique-sur-le-bouton-r%C3%A9diger-un-message-je-scrolle-vers-le-cadre-de-r%C3%A9daction-de-message-en-bas-de-page)

2022-07-20 16:41 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Instructeur, je reçois un mail lorsqu'un demandeur a posté un message sur une demande qui fait partie de mes APIs instruites](https://trello.com/c/fOIPGVnc/1507-etq-instructeur-je-re%C3%A7ois-un-mail-lorsquun-demandeur-a-post%C3%A9-un-message-sur-une-demande-qui-fait-partie-de-mes-apis-instruites)

2022-07-27 14:47 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U, lorsque je clique sur "Envoyer votre message", je vois mon message apparaître dans l'historique de la demande (Sans design)](https://trello.com/c/zvWp2k8J/1495-etq-u-lorsque-je-clique-sur-envoyer-votre-message-je-vois-mon-message-appara%C3%AEtre-dans-lhistorique-de-la-demande-sans-design)

2022-07-28 10:32 UTC, rdubigny requested changes

2022-07-28 10:32 UTC, rdubigny commented on backend/app/notifiers/base_notifier.rb
> +    demandeurs_id = enrollment.demandeurs.pluck(:user_id)
```suggestion
    demandeur_ids = enrollment.demandeurs.pluck(:user_id)
```

2022-07-28 10:32 UTC, rdubigny commented on backend/app/views/enrollment_mailer/notify.text.erb
>  Vous avez un nouveau message concernant votre demande d’habilitation :
```suggestion
Vous avez un nouveau message concernant votre demande d’habilitation.
```

2022-07-28 10:32 UTC, rdubigny commented on backend/app/views/enrollment_mailer/admin/notify_instructor.text.erb
> +Merci d'en prendre connaissance via le lien suivant <%= @url %> .
```suggestion
Pour consulter cette demande d’habilitation, veuillez cliquer sur le lien suivant <%= @url %> .
```

2022-07-28 12:38 UTC, Isalafont commented on backend/app/notifiers/base_notifier.rb
> +    demandeurs_id = enrollment.demandeurs.pluck(:user_id)
Exact 👍🏻

2022-07-28 12:38 UTC, Isalafont commented on backend/app/views/enrollment_mailer/admin/notify_instructor.text.erb
> +Merci d'en prendre connaissance via le lien suivant <%= @url %> .
Thanks, this wording will be better !

2022-08-16 09:07 UTC, closed without merging