Update index.js
betagouv/datapass pull request #645
Opened 2022-07-27 15:32 UTC by SchweisguthN

Mise à jour des éditeurs en fonction des mails "Editeur avec un siret inconnu"

2022-07-27 15:39 UTC, Isalafont approved these changes

2022-07-28 10:21 UTC, rdubigny commented
@SchweisguthN est ce qu'il faut mettre à jour la base de donnée en production ? (ie. remplacer les entrées JVS-MAIRISTEM par le siret correspondant ?)

2022-07-28 10:23 UTC, rdubigny requested changes

2022-07-28 10:23 UTC, rdubigny commented on frontend/src/pages/ApiParticulier/index.js
> +  { name: 'JVS-MAIRISTEM', siret: '32855218700069' },
la casse ne correpond pas à ce qui est affiché sur le site https://www.jvs-mairistem.fr/
```suggestion
  { name: 'JVS-Mairistem', siret: '32855218700069' },
```

2022-07-28 13:37 UTC, SchweisguthN commented
@rdubigny A mon avis pas besoin. Sur API Part, on a pas de nécessité absolue d'avoir le SIRET, sauf erreur de ma part, donc je ne vois pas de besoin de mettre à jour les entrées en base.

J'ai accepté ton changement, je peux dismiss ta review ou il y a autre chose à faire ?

2022-07-29 10:14 UTC, rdubigny commented
> @rdubigny A mon avis pas besoin. Sur API Part, on a pas de nécessité absolue d'avoir le SIRET, sauf erreur de ma part, donc je ne vois pas de besoin de mettre à jour les entrées en base.
> 
> J'ai accepté ton changement, je peux dismiss ta review ou il y a autre chose à faire ?

Le problème que je vois c'est qu'on est pas capable de sélectionner les cas d'usages dans ce cas. Mais ça intervient peut être avant.

Un autre problème c'est qu'on va avoir du mal a faire des stats.

Est ce que ça te va si je pousse un petit script qui fait la migration ? ça me prend 10 minutes

2022-07-29 10:17 UTC, rdubigny approved these changes

2022-07-29 10:21 UTC, merged