Add column to count messages
betagouv/datapass pull request #682
Opened 2022-08-19 15:57 UTC by Isalafont

add a new color var dark-grey
<img width="1248" alt="Capture d’écran 2022-08-19 à 17 54 53" src="https://user-images.githubusercontent.com/43042737/185659173-96467218-484f-413d-a8f2-7113e4b13e61.png">

2022-08-19 16:01 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Instructeur, je vois la colonne notification sur le dashboard](https://trello.com/c/iZe3jHbH/1501-etq-instructeur-je-vois-la-colonne-notification-sur-le-dashboard)

2022-08-24 13:39 UTC, rdubigny commented
hello @Isalafont ! lorsque je suis sur l'onglet "habilitations traitées" il n'y a plus de pastille, je pense que ce serait bien de l'ajouter là aussi. 

![image](https://user-images.githubusercontent.com/4190728/186433198-d4f275c6-38d2-49fb-abe6-11468618e981.png)

2022-08-24 13:41 UTC, Isalafont commented
Effectivement, je n'avais pas traité ce cas là ! 
Je m'en occupe @rdubigny

2022-08-24 14:00 UTC, rdubigny requested changes

2022-08-24 14:00 UTC, rdubigny commented on frontend/src/components/templates/InstructorEnrollmentList.js
> +        ...enrollmentListStyle.centeredCell,
you should remove ellipsis for this collumn.
![image](https://user-images.githubusercontent.com/4190728/186438224-a5677851-f0b2-4f80-9803-8226d5d15b9b.png)


ex: 

```css
td_element {
  text-overflow: unset;
}
```

2022-08-24 14:23 UTC, Isalafont commented on backend/app/serializers/light_enrollment_serializer.rb
> +  attributes :id, :updated_at, :nom_raison_sociale, :target_api, :status, :demandeurs, :count_notify_events_from_demandeurs
Is it ? This name seems a little bit confusing to me, or maybe `notify_events_from_demandeurs_counter` would be better ?

2022-08-24 14:27 UTC, Isalafont commented on backend/app/serializers/light_enrollment_serializer.rb
> +  attributes :id, :updated_at, :nom_raison_sociale, :target_api, :status, :demandeurs, :count_notify_events_from_demandeurs
or we can use `count_demandeur_notify_events` so we keep the same guideline than for `mark_demandeur_notify_events_as_processed`

2022-08-24 15:20 UTC, rdubigny approved these changes

2022-08-24 15:21 UTC, merged