Feat/messagerie/instructor see all unread messages
betagouv/datapass pull request #702
Opened 2022-08-24 15:50 UTC by Isalafont

2022-08-24 16:07 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ instructeur, si j'ai un ou plusieurs messages non lus, je vois tous les événements jusqu'au message non lu le plus ancien](https://trello.com/c/1pqSw4qg/1541-etq-instructeur-si-jai-un-ou-plusieurs-messages-non-lus-je-vois-tous-les-%C3%A9v%C3%A9nements-jusquau-message-non-lu-le-plus-ancien)

2022-08-24 16:08 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refacto: Creation d'un helper "getDemandeurEmail"](https://trello.com/c/halPeOHd/1539-refacto-creation-dun-helper-getdemandeuremail)

2022-08-25 14:12 UTC, rdubigny requested changes
J'ai rebase la branche. pense à bien rebase cette branche `git pull --rebase origin feat/messagerie/instructor-see-all-unread-messages` avant d'apporter des modifications.

2022-08-25 14:12 UTC, rdubigny commented on frontend/src/components/organisms/form-sections/HeadSection/ActivityFeed.js
> +      : (eventsToDisplay = [last(eventsToDisplay)]);
cette implémentation ne marche pas si le dernier évenement n'est pas une notification. De plus, l'implémentation dont on a discuté parlait plutôt d'afficher tous les évenements jusqu'au dernier message non traité. Or, ton implémentation affiche uniquement les messages. Je te propose qu'on s'en tienne à l'implémentation dont on avait discuté avec Nico : 

```javascript
  if (!showDetails && events.length > 0) {
    const showFromIndex = eventsToDisplay.findIndex(
      ({ name, user, processed_at }) =>
        name === 'notify' &&
        getDemandeursEmails({ team_members }).includes(user.email) &&
        processed_at === null
    );
    // if there is no message from the demandeur then showFromIndex === -1
    // as a consequence, slice only take the last event from eventsToDisplay
    eventsToDisplay = eventsToDisplay.slice(showFromIndex);
  }
```

2022-08-25 14:12 UTC, rdubigny commented on frontend/src/components/organisms/form-sections/HeadSection/NotificationSubSection.js
> +            countMessage={notify_events_from_demandeurs_count}
countMessage => messageCount

2022-08-25 14:46 UTC, rdubigny approved these changes

2022-08-25 14:52 UTC, merged