add demandeur name and email in notif_email_to_instructor template.
betagouv/datapass pull request #726
Opened 2022-09-12 15:14 UTC by Isalafont

2022-09-12 15:15 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ instructeur, je vois l'adresse email du demandeur dans l'email de notification d'un nouveau message](https://trello.com/c/FRXQf9TC/1547-etq-instructeur-je-vois-ladresse-email-du-demandeur-dans-lemail-de-notification-dun-nouveau-message)

2022-09-13 13:33 UTC, rdubigny requested changes

2022-09-13 13:33 UTC, rdubigny commented on backend/app/views/enrollment_mailer/admin/notification_email_to_instructors.text.erb
> +Vous avez un nouveau message de <%= @demandeur.given_name %> <%= @demandeur.family_name %> (adresse email :<%= @demandeur_email %>) concernant une demande d’habilitation :
There are spaces arround double dot

2022-09-13 13:33 UTC, rdubigny commented on backend/app/mailers/enrollment_mailer.rb
> +    @demandeur_email = @enrollment.demandeurs.pluck(:email).first
these variable usage is not very consistent, either:
1. use a single `@demandeur` variable and read its attributes in the template
2. or define 3 variables here.

2022-09-14 09:43 UTC, rdubigny approved these changes

2022-09-14 09:54 UTC, merged