Chore/security fix/validate format file
betagouv/datapass pull request #746
Opened 2022-09-20 15:09 UTC by Isalafont

2022-09-20 15:19 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix : valider le format des fichiers "expression de besoin" (pour l'api impot particulier) et "maquette projet"](https://trello.com/c/R4whbLZd/752-fix-valider-le-format-des-fichiers-expression-de-besoin-pour-lapi-impot-particulier-et-maquette-projet)

2022-10-03 16:00 UTC, rdubigny requested changes
Cool PR!

Have you find a way to use the spreadsheed docs you added in `backend/spec/fixtures/` in the tests ?

2022-10-04 15:31 UTC, Isalafont commented on backend/app/services/magic_spreadsheet_validator.rb
> +class MagicSpreadsheetValidator
Done :)

2022-10-04 15:33 UTC, Isalafont commented on backend/app/services/magic_spreadsheet_validator.rb
> +    @starting_signature.start_with?(*VALID_STARTING_SIGNATURE)
`magic_spreadsheet_validator.rb` will inherite now from `magic_validator.rb,`

2022-10-05 12:50 UTC, Isalafont commented on backend/app/models/document/geo_shape.rb
> +class Document::GeoShape < PdfDocument
Done

2022-10-05 12:51 UTC, Isalafont commented
@rdubigny I'm using them in the document_spec.rb to test the file validations.

2022-10-07 15:24 UTC, rdubigny approved these changes

2022-10-07 15:25 UTC, merged