Unify Table on EnrollmentList
betagouv/datapass pull request #807
Opened 2022-10-18 15:09 UTC by pierreericgarcia

https://trello.com/c/4hehjqzq/1599-unifier-tous-les-tables-de-lapp-sur-le-m%C3%AAme-composant

2022-10-24 16:07 UTC, rdubigny requested changes
Nice work!

the previouslySelectedEnrollmentId feature does not seems to work anymore.

2022-10-24 16:07 UTC, rdubigny commented on frontend/src/hooks/useQueryString.ts
> +import { useState, useEffect } from 'react';
not a fan of creating folder with only one file in it. Maybe you could reuse `src/templates/hooks` ?

Careful with the file name too: custom hooks should be kebab-cased

2022-10-24 16:07 UTC, rdubigny commented on frontend/src/components/templates/InstructorEnrollmentList.js
> +      pageSize: 10,
do we realy want page size to be customisable ?

2022-10-24 16:07 UTC, rdubigny commented on frontend/src/components/templates/InstructorEnrollmentList.js
> +      pageSize: 10,
this might cause issue with bakend hard limit from the backend

2022-10-24 16:24 UTC, rdubigny commented on frontend/src/components/templates/InstructorEnrollmentList.js
> +      header: () => <ScheduleIcon color={'var(--datapass-dark-grey)'} />,
on reprend là

2022-10-24 16:30 UTC, rdubigny requested changes
![image](https://user-images.githubusercontent.com/4190728/197577407-7f9704e7-e69d-4883-9e8c-33fcb0017991.png)

1. date-time should not be in read
2. get back the useful alt-text for update_at & notification count collumn (header & row)
3. list should have a default sorting value

2022-10-26 14:45 UTC, pierreericgarcia commented on frontend/src/hooks/useQueryString.ts
> +const setQueryStringValue = (key: string, value: any) => {
I don't understand, I use it

2022-10-26 15:23 UTC, pierreericgarcia commented on frontend/src/components/templates/InstructorEnrollmentList.js
> +            manualPagination: true,
I think this API abstraction refinement of the `Table` component can be done in an other task

2022-11-01 15:11 UTC, rdubigny requested changes
Hello @pierreericgarcia !

J'ai 2 erreurs en console :

![image](https://user-images.githubusercontent.com/4190728/199255671-86633491-2095-47e9-aa06-326bd0f71e38.png)

![image](https://user-images.githubusercontent.com/4190728/199255741-dc0f1321-c6e8-4c5f-85d9-402388d17d16.png)

Je te laisse regarder.

Par ailleurs, je ne suis pas fan de la pagination sur la page FAQ : 

![image](https://user-images.githubusercontent.com/4190728/199259659-245d6c2e-ffe9-4095-99c1-1d0c63aba1f9.png)

Est ce que tu peux ajouter cet élément à la liste des choses à valider par @renardpal ?

Concernant le tri par date : il faut aussi remettre à zero la page actuel lorsqu'on active le tri. De plus, il ne faut pas permettre un ordre non trié, soit on trie par date croissante soit par date décroissante.

Concernant la colonne date : la notation 4j n'est plus adaptée, il faut mettre une notation de type : JJ/MM/YY (ou JJ/MM) à la place. Par ailleurs, un hover sur la colonne donne toujours la même date (1er janvier 1970) ? Est ce que c'est un problème avec mon navigateur ?

2022-11-01 18:31 UTC, rdubigny commented on frontend/src/components/atoms/hyperTexts/Badge.tsx
> +  type?: BadgeType | '';
à la réflection, le type devrait soit être un BadgeType soit null. Je trouve que ça a plus de sens qu'un type qui vaut `''`

2022-11-02 14:10 UTC, rdubigny commented on frontend/src/components/molecules/FilterComponent/index.tsx
> +        onChange={(e: React.SyntheticEvent) => {
tu vas me haïr, mais est ce que c'est possible d'utiliser un type plus précis : ChangeEventHandler<HTMLInputElement> ?

2022-11-03 15:26 UTC, rdubigny reviewed
À notre qu'avec cette PR, le tableau ne s'affiche plus en entier avec un écran d'une largeur inférieure à 1000px de large. Ce n'est peut être pas un soucis mais il peut être intéressant de le mentionner à Nicolas et Amandine.

2022-11-03 15:26 UTC, rdubigny commented on frontend/src/components/atoms/hyperTexts/Badge.tsx
> +  type?: BadgeType | null;
en fait, je viens de voir que type est optionnel, donc pour moi pas besoin de mettre le null. Sry

```suggestion
  type?: BadgeType;
```

2022-11-03 15:26 UTC, rdubigny commented on frontend/src/components/atoms/hyperTexts/Badge.tsx
> +  type = '',
en conséquence pas besoin de mettre une valeur par défaut ici :
```suggestion
  type,
```

2022-11-03 17:21 UTC, rdubigny approved these changes

2022-11-03 17:23 UTC, merged