Chore/import mire api
betagouv/datapass pull request #810
Opened 2022-10-20 12:15 UTC by Isalafont

2022-10-26 12:53 UTC, Isalafont commented
Pense Bête 
Rajouter une Variable d'environnement `API_GOUV_HOST` dans l'environnement de production

2022-10-27 11:25 UTC, Isalafont commented
💡 Rajouter variable d'env `API_GOUV_HOST` en production pour le backend

2022-11-01 14:17 UTC, rdubigny requested changes
Hello @Isalafont !

Sur la page /data-providers/api, quand je clique sur remplir une demande, je suis redirigé sur une route du backend en 404.

Par ailleurs, j'ai beaucoup trop de logs en backend.

Je te laisse corriger ces 2 points avant de lire la suite.

2022-11-01 14:17 UTC, rdubigny commented on backend/app/controllers/api_gouv_controller.rb
> +  def apis_list
utilise soit le pluriel pour api soit le mot "list" avec api au singulier, mais pas les deux.

2022-11-02 09:04 UTC, Isalafont commented
@rdubigny 

`Sur la page /data-providers/api, quand je clique sur remplir une demande, je suis redirigé sur une route du backend en 404.`


Est ce que tu as dans ton fichier `env` du front rajouter la variable `REACT_APP_BACK_HOST=http://localhost:3000` ? 
J'aurais une question à ce sujet : Est ce que l'on veut que dans l'environnement localhost, on soit renvoyé sur les formulaires `localhost:3000/api-....` ou sur les formulaire avec l'adresse `datapass-staging` en local ET environnement développement. 

Pour les logs, je vais vérifier comment les supprimer, effectivement il y en a beaucoup.

2022-11-02 09:35 UTC, Isalafont commented on backend/app/controllers/api_gouv_controller.rb
> +  def apis_list
Je vais modifier cela en `apis`, c'est effectivement plus logique et fera un URL également plus court !

2022-11-03 16:02 UTC, rdubigny requested changes

2022-11-03 16:02 UTC, rdubigny commented on frontend/src/components/templates/DataProviderList/DataProviderListHubee.tsx
> +const DataProvidersHubee = [
DataProvidersHubee => HubeeDataProviders

2022-11-03 16:02 UTC, rdubigny commented on frontend/src/components/templates/DataProviderList/DataProviderListApi.tsx
> +  async function getApisList() {
put this in a service

2022-11-03 16:02 UTC, rdubigny commented on frontend/src/components/templates/DataProviderList/DataProviderListApi.tsx
> +        `${FRONT_HOST}/api/api_gouv/apis`
FRONT_HOST => BACK_HOST

2022-11-03 16:02 UTC, rdubigny commented on frontend/src/components/templates/DataProviderList/DataProviderListApi.tsx
> +        console.log('error message: ', error.message);
remove all console logs

2022-11-08 13:29 UTC, rdubigny approved these changes

2022-11-08 13:29 UTC, rdubigny commented on backend/app/services/api_gouv.rb
> +    # Add Impot particulier fc hash in apis list as it is not generate in the api.gouv.fr/api/v1/
```suggestion
    # Add Impot particulier fc hash in api list as it is not generated in the api.gouv.fr/api/v1/ endpoint
```

2022-11-08 17:34 UTC, merged