Feat/api france connecté scope name in email
betagouv/datapass pull request #832
Opened 2022-11-02 16:36 UTC by Isalafont

Ajout de scopes pour les api France Connecté suivantes : 

- api_droits_cnam
- api_indemnisation_pole_emploi
- api_indemnites_journalieres_cnam
- api_status_demandeur_emploi
- api_statut_etudiant_boursier

⚠️ En attente de validation pour l'api Impot Particulier FC

![Capture d’écran 2022-11-02 à 17 17 19](https://user-images.githubusercontent.com/43042737/199548063-f785314f-e225-4545-9ddd-ae04f02ba2a6.png)
![Capture d’écran 2022-11-02 à 17 22 39](https://user-images.githubusercontent.com/43042737/199548073-2f3ba446-a6b0-4d77-8fcb-aaa751520192.png)

2022-11-02 16:39 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Demandeur d'une API FC, lorsque ma demande est validée, on me donne le nom des scopes (nom technique pour implémentation)](https://trello.com/c/Frgl8DCv/1565-etq-demandeur-dune-api-fc-lorsque-ma-demande-est-valid%C3%A9e-on-me-donne-le-nom-des-scopes-nom-technique-pour-impl%C3%A9mentation)

2022-11-03 16:16 UTC, rdubigny requested changes
there is 9 FcDataProviderBridges and only 6 mails are added here. You might have miss some data provider.

2022-11-03 16:16 UTC, rdubigny commented on backend/app/services/enrollment_email_templates_retriever.rb
> +  end
I do not think this simplify the readability.

2022-11-03 16:16 UTC, rdubigny commented on backend/app/views/enrollment_mailer/api_droits_cnam/validate.text.erb
> +L’équipe <%= @target_api_label %>
plz add new lines at every end of file.

2022-11-03 16:20 UTC, Isalafont commented on backend/app/views/enrollment_mailer/api_droits_cnam/validate.text.erb
> +L’équipe <%= @target_api_label %>
damned.... will do right away !

2022-11-04 07:59 UTC, Isalafont commented
Right! 
Does this missing apis should not appear too on the research of api france connecté on api.gouv.fr ?

2022-11-17 13:14 UTC, rdubigny approved these changes

2022-11-17 13:15 UTC, merged