New table date & message sort
betagouv/datapass pull request #844
Opened 2022-11-08 14:44 UTC by pierreericgarcia

2022-11-14 10:16 UTC, Isalafont commented
![Capture d’écran 2022-11-14 à 11 08 35](https://user-images.githubusercontent.com/43042737/201633175-d732f751-a475-40aa-8d16-06127865f340.png)

La Migration semble à revoir. 
Le user_id 1 est 1 administrateur/instructor et la migration l'a quand même passé en `is_notified_from_demandeur: true` au lieu de le garder en false.

2022-11-17 15:17 UTC, rdubigny requested changes
Nice PR!

Can you  rebase it on master ?

2022-11-17 15:17 UTC, rdubigny commented on frontend/src/components/organisms/Table/index.tsx
> +                      return (
a component with nested `return`s? we could use a new component here.

2022-11-17 15:17 UTC, rdubigny commented on frontend/src/components/templates/InstructorEnrollmentList.tsx
> +  FilterFn,
mind the github warning here: 'FilterFn' is defined but never used

2022-11-18 08:57 UTC, rdubigny commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ instructeur, je vois le nouveau design de la colonne Date](https://trello.com/c/ZWFpqnkk/1635-etq-instructeur-je-vois-le-nouveau-design-de-la-colonne-date)

2022-11-21 12:49 UTC, pierreericgarcia commented on backend/db/migrate/20221109155011_add_is_notified_from_demandeur_to_events.rb
> +        add_column :events, :is_notified_from_demandeur, :boolean, default: false
I don't agree with your recommendation as this action (`notify`) was done in the past

2022-11-21 12:49 UTC, pierreericgarcia commented on backend/app/models/event.rb
> +  def mark_as_notified_from_demandeur
Same as precedent comment I found the preterit form more adapted

2022-11-22 10:10 UTC, pierreericgarcia commented on backend/db/migrate/20221109155011_add_is_notified_from_demandeur_to_events.rb
> +        add_column :events, :is_notified_from_demandeur, :boolean, default: false
zrrgrg

2022-11-24 15:46 UTC, rdubigny approved these changes

2022-11-24 15:46 UTC, merged