ETQ U non logué, je vois le bouton "Mon Compte Pro" sur la home au lieu de "Me Connecter"
betagouv/datapass pull request #859
Opened 2022-11-16 15:31 UTC by Isalafont

Remove btn "Creer un compte" and replace it with "Se connecter avec MonComptePro"

![Capture d’écran 2022-11-16 à 16 07 24](https://user-images.githubusercontent.com/43042737/202223408-2ed4f231-c447-4cb0-8b73-1c48fbc1bb9a.png)

2022-11-16 15:35 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U non logué, je vois le bouton "Mon Compte Pro" sur la home au lieu de "Me Connecter"](https://trello.com/c/u18wZcQc/1659-etq-u-non-logu%C3%A9-je-vois-le-bouton-mon-compte-pro-sur-la-home-au-lieu-de-me-connecter)

2022-11-16 16:40 UTC, rdubigny requested changes

2022-11-16 16:40 UTC, rdubigny commented on frontend/src/components/templates/Login/index.js
>  const LoginButtons = ({ isOnNewEnrollmentPage }) => (
I think that you can remove the LoginButtons component and put the form in the MonComptePro component

2022-11-16 16:40 UTC, rdubigny commented on frontend/src/components/atoms/MonComptePro/MonComptePro.tsx
> +};
none of these props are used, you can remove it.

2022-11-16 16:40 UTC, rdubigny commented on frontend/src/components/templates/Login/index.js
>    <div className="login-buttons">
If you delete this component, mind the suppression of the css rule binded to `.login-buttons` if any.

2022-11-17 15:48 UTC, rdubigny requested changes

2022-11-17 15:48 UTC, rdubigny commented on frontend/src/components/templates/Login/index.js
> +            <MonComptePro isOnNewEnrollmentPage={isOnNewEnrollmentPage} />
this props is not used, plz remove it.

2022-11-17 15:50 UTC, rdubigny requested changes

2022-11-17 15:50 UTC, rdubigny commented on frontend/src/components/atoms/MonComptePro/style.css
> +  color: var(--text-action-blue-france);
not needed, the link should be grey when visited. We should stick on the DSFR here.

2022-11-17 16:25 UTC, rdubigny approved these changes

2022-11-17 16:28 UTC, merged