Align table headers
betagouv/datapass pull request #892
Opened 2022-12-05 10:32 UTC by pierreericgarcia

2022-12-05 10:32 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U, je vois les titres des colonnes de la liste des habilitations alignés](https://trello.com/c/LatTcCHa/1664-etq-u-je-vois-les-titres-des-colonnes-de-la-liste-des-habilitations-align%C3%A9s)

2022-12-08 11:02 UTC, rdubigny requested changes
checkboxes are not align with labels anymore:

![image](https://user-images.githubusercontent.com/4190728/206425586-ef28819a-8bab-4c10-9eea-5aeec96a32bb.png)

there is too much space here:

![image](https://user-images.githubusercontent.com/4190728/206427526-0411b667-ee7b-4280-9fee-a13d7b53d603.png)

2022-12-08 11:02 UTC, rdubigny commented on frontend/src/components/atoms/inputs/Input.js
> +  if (label) {
The usage of input without label is forbidden by the dsfr and make the input not accessible. This usage should not be encouraged in my opinion. I'd rather use the <input> react element directly in the table header 🤔

2022-12-21 09:49 UTC, rdubigny requested changes

2022-12-21 09:49 UTC, rdubigny commented on frontend/src/components/organisms/Table/style.css
> +.fr-label + .fr-input, .fr-label + .fr-input-wrap, .fr-label + .fr-select {
this rule is not selective enought and can have unexpected effect on the app. Plz scope this under .datapass-table selector.

2022-12-21 09:55 UTC, rdubigny approved these changes

2022-12-21 10:04 UTC, merged