Better copy error messages ⚠️
betagouv/datapass pull request #893
Opened 2022-12-05 15:39 UTC by pierreericgarcia

More precise and detailed copy error messages.

2022-12-05 15:40 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U, je vois une page d'erreur plus pédagogue en cas d'erreur de copie d'une demande](https://trello.com/c/MTUHOhyD/1646-etq-u-je-vois-une-page-derreur-plus-p%C3%A9dagogue-en-cas-derreur-de-copie-dune-demande)

2022-12-07 10:29 UTC, skelz0r requested changes
cf coms.

de plus: où sont les tests ?

2022-12-07 10:29 UTC, skelz0r commented on backend/app/controllers/application_controller.rb
> +      }
Histoire d'être plus DRY, je refactoriserai cette construction (même trivial) dans une méthode `build_error`:

```ruby
def build_error(title:, message:)
  {
    "title" => title,
    "message" => message
  }
end
```

2022-12-07 10:29 UTC, skelz0r commented on backend/app/models/enrollment.rb
> +  end
Généralement on utilise des méthodes avec des `?` pour traduire le caractère booléen en ruby.

Je propose `already_been_copied?`

ça donne en interface: `enrollment.already_been_copied?` ce qui est compréhensible.

2022-12-07 10:29 UTC, skelz0r commented on backend/app/policies/enrollment_policy.rb
> +    if record.copied_from_enrollment_id?
je pense que ça ne marche pas ça (mais pas 100% sûr)

imo le mieux serait de faire une méthode dans l'enrollment:

```ruby
def copy?
  copied_from_enrollment_id.present?
end
```

2022-12-07 10:29 UTC, skelz0r commented on backend/app/policies/enrollment_policy.rb
> +      @error_message_key = :copy_enrollment_is_a_copy
```suggestion
      @error_message_key = :enrollment_is_a_copy
```

ce `copy_` devant ne sert à rien, la clé me semble plus explicite comme ça

2022-12-07 10:29 UTC, skelz0r commented on backend/app/policies/enrollment_policy.rb
> +      @error_message_key = :copy_enrollment_has_already_been_copied
```suggestion
      @error_message_key = :enrollment_has_already_been_copied
```

2022-12-07 10:29 UTC, skelz0r commented on backend/app/controllers/application_controller.rb
> +        "title" => "Vous ne faites pas partie de l'organisation de l'habilitation initiale",
Clairement ici tu pourrais utiliser de l'i18n pour directement lookup les messages:

dans `config/locales/fr.yml`:

```yaml
fr:
  enrollment_errors:
    user_do_not_belong_to_organization:
      title: "Vous ne faites pas partie de l'organisation de l'habilitation initiale"
      message: "L'habilitation que vous essayez de copier a été accordée à une organisation dont vous ne faites pas partie. Si l'organisation initiale n'existe plus, la copie de la demande initiale n'est pas possible : merci de soumettre une nouvelle demande."
```

dans le code:

```ruby
I18n.t("enrollment_errors.#{error_key}")
```

bonus point: les traductions sont dans un fichier YAML les équipes content/product peuvent changer sans toucher le code.

2022-12-07 11:04 UTC, pierreericgarcia commented on backend/app/policies/enrollment_policy.rb
> +      @error_message_key = :copy_enrollment_is_a_copy
C'était pour suivre la convention de naming des clefs précédentes, dans ce cas-là même `copy_user_is_not_demandeur`pourrait être transformé en `user_is_not_demandeur` et ainsi de suite

2022-12-07 11:06 UTC, pierreericgarcia commented on backend/app/policies/enrollment_policy.rb
> +      @error_message_key = :copy_enrollment_has_already_been_copied
Same

2022-12-07 11:07 UTC, pierreericgarcia commented on backend/app/controllers/application_controller.rb
> +        "title" => "Vous ne faites pas partie de l'organisation de l'habilitation initiale",
Je trouve que c'est une bonne idée effectivement, actuellement on le fait nul part dans le backend. Peut-être que ça pourrait faire parti de la refacto des messages d'erreur, qu'en penses-tu @rdubigny ?

2022-12-07 14:31 UTC, skelz0r reviewed
Je vois que l'approche i18n n'a pas été retenue, dommage 🤷

modulo mes 2/3 suggestions c'est ok pour moi then

2022-12-07 14:31 UTC, skelz0r commented on backend/spec/controllers/enrollments/copy_spec.rb
> +            end
```suggestion
            context "when enrollment has already been copied" do
              before do
                enrollment.copy user
              end
                
              it { is_expected.to have_http_status(:forbidden) }
            end
```

2022-12-07 14:31 UTC, skelz0r commented on backend/app/models/enrollment.rb
> +    copied_enrollment.present?
```suggestion
    Enrollment.where(copied_from_enrollment_id: id).any?
```

ça speed-up le sql ici (`any?` est traduit en SQL)

2022-12-08 11:21 UTC, rdubigny requested changes
If you want to offer me a christmas present you could replace all single quote `'` within french sentences by an apostrophe `’` 🎅🏻

2022-12-22 07:13 UTC, merged