Public Listing Enhance + Filter Service 🎁
betagouv/datapass pull request #912
Opened 2022-12-16 16:26 UTC by pierreericgarcia

2022-12-16 16:26 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U de la page publique de liste des habilitations, les informations sont paginées côté serveur](https://trello.com/c/MZwqvt7U/1705-etq-u-de-la-page-publique-de-liste-des-habilitations-les-informations-sont-pagin%C3%A9es-c%C3%B4t%C3%A9-serveur)

2022-12-16 16:26 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [Backend : Créer un service Filter](https://trello.com/c/C6AaA9Sb/1697-backend-cr%C3%A9er-un-service-filter)

2023-01-04 11:10 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U, je vois un tableau uniformisé entre la liste des habilitations et la page publique de liste des habilitations](https://trello.com/c/zSIUwxyR/1708-etq-u-je-vois-un-tableau-uniformis%C3%A9-entre-la-liste-des-habilitations-et-la-page-publique-de-liste-des-habilitations)

2023-01-04 11:11 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U de la page publique de liste des habilitations, lorsque je filtre sur un champ (en cliquant sur l'en-tête), le filtre s'applique à l'ensemble des données, et pas aux données affichées](https://trello.com/c/FxZYOWa9/1673-etq-u-de-la-page-publique-de-liste-des-habilitations-lorsque-je-filtre-sur-un-champ-en-cliquant-sur-len-t%C3%AAte-le-filtre-sapplique)

2023-01-05 16:23 UTC, rdubigny submitted a review, later dismissed

2023-01-05 16:23 UTC, rdubigny commented on backend/app/services/filter_service.rb
> +class FilterService < ApplicationService
can we use this service here : https://github.com/betagouv/datapass/blob/chore/enrollments-public-listing-pagination/backend/app/controllers/users_controller.rb#L13-L38 ?

2023-01-16 12:46 UTC, rdubigny requested changes

2023-01-16 14:44 UTC, rdubigny requested changes
Nice job on rails ;)

I added a few comments.

2023-01-16 14:44 UTC, rdubigny commented on backend/app/controllers/enrollments_controller.rb
> +      @enrollments = FilterService.new(params).call(@enrollments)
this function signature is quite strange. I'm expecting to have only on fonction to call like so:

```
FilterService.call(params, @enrollments)
```

2023-01-16 17:53 UTC, rdubigny submitted a review, later dismissed
cool PR, a few bugs remain though.

there are errors in console on /public:

![image](https://user-images.githubusercontent.com/4190728/212739327-8b0411d3-1f55-4427-88a0-b1d190d02e32.png)

on /stats , these links are broken:

![image](https://user-images.githubusercontent.com/4190728/212739454-b863ab3a-9069-4be0-9554-1f15047211ff.png)

on /public, sorting is enabled put it sorts only the actual page:

![image](https://user-images.githubusercontent.com/4190728/212739581-a26aa11d-6b87-405b-9116-4ae0f962a941.png)

strange behavior, after a query that returns no result, if we get back to a query with results the page is zero:

![image](https://user-images.githubusercontent.com/4190728/212740242-076cd9a1-b5ad-4a7c-a384-33c2f4891e4e.png)

2023-01-24 10:50 UTC, rdubigny requested changes
There is still a bug : 

after a query that returns no result, if we get back to a query with results, the first time I hit "suivant" the page does not change.

Plus, a user with no access rights see this on the /public page:

![image](https://user-images.githubusercontent.com/4190728/214272776-e7d5ace7-ef07-448d-bc59-0b5aa8b6398b.png)

2023-01-25 18:26 UTC, rdubigny approved these changes

2023-01-25 18:26 UTC, merged