New Login Button 💅
betagouv/datapass pull request #925
Opened 2023-01-04 15:39 UTC by pierreericgarcia

2023-01-04 15:39 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mise à jour du btn de connexion selon les reco du DSFR](https://trello.com/c/g3X3l28i/1680-mise-%C3%A0-jour-du-btn-de-connexion-selon-les-reco-du-dsfr)

2023-01-16 10:05 UTC, Isalafont commented on frontend/src/components/atoms/hyperTexts/HyperText.tsx
>    }
Cool PR ! 
Est ce que l'utilisation d'un if imbriqué dans un autre if est bien la meilleure option ? 
Ne peut on pas utiliser un ternary operator à la place ? 
```
if (icon) {
    className += iconFill ? ` fr-icon-${icon}-fill` : ` fr-icon-${icon}-line`;
  }
  ```

2023-01-16 16:53 UTC, rdubigny requested changes
There is some breaking change with the update of the dsfr library:

- ![image](https://user-images.githubusercontent.com/4190728/212729501-b1656a82-90b4-4920-abf6-db6dd7a31af2.png)

- ![image](https://user-images.githubusercontent.com/4190728/212729598-6085cdb3-ff55-46ab-9f7f-f05c4984cd07.png)

- horizontal scrolling on form page

weird:

![image](https://user-images.githubusercontent.com/4190728/212730424-638f6df6-a6a9-4f66-895b-a0e6a0154793.png)

2023-01-18 10:32 UTC, Isalafont approved these changes

2023-01-18 10:33 UTC, Isalafont commented
Il y a toujours ce conflit = 
Conflicting files
frontend/src/components/atoms/icons/fr-fi-icons.tsx

2023-01-18 12:33 UTC, merged