Archive 🗂
betagouv/datapass pull request #929
Opened 2023-01-10 14:31 UTC by pierreericgarcia

Face à l'abondance d'emojis symbolisant un classeur, une intercalaire ou un rangement, j'hésite :

1. 🗃
2. 🗄
3. 📁
4. 📂
5. 🗂
6. 📒

2023-01-10 16:19 UTC, pierreericgarcia commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U, je peux archiver une habilitation](https://trello.com/c/mxH9KEqX/1690-etq-u-je-peux-archiver-une-habilitation)

2023-01-16 14:39 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Demandeur ayant au moins une demande en A modifier depuis 6 mois ou plus, je reçois un email me prévenant de sa suppression prochaine](https://trello.com/c/LQjLpPg3/1707-etq-demandeur-ayant-au-moins-une-demande-en-a-modifier-depuis-6-mois-ou-plus-je-re%C3%A7ois-un-email-me-pr%C3%A9venant-de-sa-suppression-p)

2023-01-24 10:34 UTC, rdubigny requested changes

2023-01-24 10:34 UTC, rdubigny commented on backend/spec/controllers/enrollments/export_spec.rb
> +      expect { subject }.to make_database_queries(count: 4)
This is a performance regression. We must keep the number of database query to 3.

2023-01-24 10:34 UTC, rdubigny commented on backend/app/policies/enrollment_policy.rb
> +    if record.status_archived?
this condition is not necessary as the condition `(record.status_draft? || record.status_changes_requested?)` below imply it

2023-01-24 10:34 UTC, rdubigny commented on backend/app/policies/enrollment_policy.rb
> +    if record.status_archived?
we could also keep the onliner synthax:

`!record.status_archived? && (user.is_member?(record) || user.is_reporter?(record))`

2023-01-25 08:58 UTC, pierreericgarcia commented on backend/app/views/enrollment_mailer/archive.text.erb
> +Pour consulter cette habilitation, veuillez cliquer sur le lien suivant <%= @url %> .
This mail was deleted.

2023-01-30 15:12 UTC, rdubigny requested changes

2023-01-30 15:12 UTC, rdubigny commented on frontend/src/components/templates/Form/SubmissionPanel/index.tsx
> +            title="L'archivage d'une habilitation est irréversible"
Somehow, isn't this a lie ? 🤔

2023-01-30 15:12 UTC, rdubigny commented on backend/app/policies/enrollment_policy.rb
> +    (record.can_archive_status? && user.is_instructor?(record.target_api)) || user.is_administrator?
record.can_archive_status? should always be needed, even from administrator.

2023-01-31 17:11 UTC, Isalafont approved these changes

2023-01-31 17:13 UTC, Isalafont commented
Great PR :tada: !! 
For me it's good and ready to be merged on master ! 🚀

2023-01-31 17:19 UTC, Isalafont approved these changes

2023-01-31 17:35 UTC, merged