Chore/picto unique message instructeur
betagouv/datapass pull request #937
Opened 2023-01-18 14:43 UTC by Isalafont

2023-01-18 14:45 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ instructeur, j'ai un picto unique que j'aie un ou plusieurs messages non lus](https://trello.com/c/FapWWwEx/1678-etq-instructeur-jai-un-picto-unique-que-jaie-un-ou-plusieurs-messages-non-lus)

2023-01-18 14:54 UTC, pierreericgarcia commented
Yo Isabelle, c'est pas la bonne couleur pour l’icône représentant que tous les messages ont été lus.

<img width="56" alt="Capture d’écran 2023-01-18 à 15 52 44" src="https://user-images.githubusercontent.com/26710696/213203594-e9246b76-b8cd-4534-8725-3ad08ede309c.png">

De plus les tests E2E passent pas, je t'invite à les relancer et fixer cette histoire de couleur je passerais à la relecture technique juste après.

*se tranforme en @rdubigny*

2023-01-18 15:14 UTC, Isalafont commented
@pierreericgarcia merci ! Je viens de changer la couleur et je repasserais les tests End2End lorsque l'INSEE ne fera plus des siennes (vers 18h?)
👍

2023-01-24 14:07 UTC, rdubigny requested changes

2023-01-24 14:07 UTC, rdubigny commented on frontend/src/components/templates/InstructorEnrollmentList.css
> +  position:relative;
this css file has no consistent formating (no space after `:`)

2023-01-24 14:09 UTC, rdubigny approved these changes

2023-01-24 14:14 UTC, merged