Feat/change requested enrollments 6 months old send remail
betagouv/datapass pull request #961
Opened 2023-02-02 17:46 UTC by Isalafont

2023-02-03 11:17 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ Demandeur ayant au moins une demande en A modifier depuis 6 mois ou plus, je reçois un email me prévenant de son archivage prochain](https://trello.com/c/LQjLpPg3/1707-etq-demandeur-ayant-au-moins-une-demande-en-a-modifier-depuis-6-mois-ou-plus-je-re%C3%A7ois-un-email-me-pr%C3%A9venant-de-son-archivage-pr)

2023-02-23 15:17 UTC, rdubigny approved these changes

2023-02-23 15:48 UTC, pierreericgarcia requested changes

2023-02-23 15:48 UTC, pierreericgarcia commented on backend/app/views/enrollment_mailer/demandeur/reminder_changes_requested_enrollment.text.erb
> +Dans un souci d’archivage des demandes n'étant plus d’actualités, nous supprimerons bientôt toutes les demandes d’habilitation concernées.
If you're going to archive them, why are you talking about deleting them ?

2023-02-23 15:48 UTC, pierreericgarcia commented on backend/app/views/enrollment_mailer/demandeur/reminder_changes_requested_enrollment.text.erb
> +Vous ne souhaitez pas que cette habilitation soit supprimée ? Deux options s’offrent à vous :
Same

2023-03-02 11:06 UTC, SchweisguthN approved these changes

2023-03-03 10:11 UTC, merged