Chore/new form presentation pages
betagouv/datapass pull request #975
Opened 2023-02-15 16:33 UTC by Isalafont

2023-02-15 16:37 UTC, Isalafont commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQ U déconnecté, je vois de nouvelles pages de présentation des formulaires](https://trello.com/c/RzeZXukw/1666-etq-u-d%C3%A9connect%C3%A9-je-vois-de-nouvelles-pages-de-pr%C3%A9sentation-des-formulaires)

2023-02-21 16:09 UTC, Isalafont commented on frontend/src/components/templates/Login/NextSteps.js
> +            {APISDGFIP.find((targetApiID) => targetApiID === targetApi)
From [developper mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) it suppose to work but  the first condition (APISDGFIP) is not working, it is displaying the default value. 

function example() {
  return condition1 ? value1
        : condition2 ? value2
        : condition3 ? value3
        : value4;
}

2023-02-21 16:16 UTC, Isalafont commented on frontend/src/components/templates/Login/NextSteps.js
> +            {APISDGFIP.find((targetApiID) => targetApiID === targetApi)
I've checked, this ternary with 2 conditions is working.

2023-02-23 09:06 UTC, pierreericgarcia requested changes

2023-02-23 09:06 UTC, pierreericgarcia commented on frontend/src/components/templates/Login/index.js
> +  const [closing, setClosing] = useState(false);
To respect state naming convention i would prefer `isClosed` and `setIsClosed`.

2023-02-23 09:06 UTC, pierreericgarcia commented on frontend/src/components/templates/Login/index.js
> +          <div style={{ backgroundColor: '#F6F6F6', height: '100%' }}>
Better use CSS classes than inline styling.

2023-02-23 09:06 UTC, pierreericgarcia commented on frontend/src/components/templates/Login/index.js
> +                src={`/images/logo-welcome-page.svg`}
No need to use backticks and `{}`, you can directly pass a string as props.

2023-02-23 09:06 UTC, pierreericgarcia commented on frontend/src/components/templates/Login/index.js
> +            <div className="panel" style={{ textAlign: 'left' }}>
No inline styling please.

2023-03-03 08:51 UTC, pierreericgarcia approved these changes

2023-03-03 08:51 UTC, merged